### ISSUE TITLE
Debian package creation failing since commit 46ba1e59d3ae7e374c7a98f15f4bef21ee3fcded

### ISSUE THREAD

**Issue by mmehnert** [openzfs/zfs#1841]
```
make[5]: Entering directory `/tmp/zfs-build-root-lSraFvTB/BUILD/zfs-0.6.2/cmd/zpool'
  CC       zpool_iter.o
  CC       zpool_main.o
  CC       zpool_util.o
  CC       zpool_vdev.o
  CCLD     zpool
../../lib/libzfs/.libs/libzfs.so: undefined reference to `lzc_rollback'
collect2: error: ld returned 1 exit status
make[5]: *** [zpool] Error 1
```

46ba1e59d3ae7e374c7a98f15f4bef21ee3fcded is the first bad commit
commit 46ba1e59d3ae7e374c7a98f15f4bef21ee3fcded
Author: Matthew Ahrens mahrens@delphix.com
Date:   Wed Aug 14 11:42:31 2013 -0800

```
Illumos #3996

3996 want a libzfs_core API to rollback to latest snapshot
```
