### ISSUE TITLE
Add kernel 3.10 support (to Daily PPA builds)

### ISSUE THREAD

**Issue by jonathonf** [openzfs/zfs#1547]
Kernel 3.10 is onto rc7 (and rc8 can't be far away). At the moment, 0.6.1 kernel modules fail to build on 3.10.

SPL DKMS make.log (ZFS not generated due to SPL failure):

make[2]: Entering directory `/var/lib/dkms/spl/0.6.1/build/module'
make -C /lib/modules/3.10.0-031000rc7-generic/build SUBDIRS=`pwd`CONFIG_SPL=m modules
make[3]: Entering directory`/usr/src/linux-headers-3.10.0-031000rc7-generic'
  CC [M]  /var/lib/dkms/spl/0.6.1/build/module/spl/../../module/spl/spl-debug.o
  CC [M]  /var/lib/dkms/spl/0.6.1/build/module/spl/../../module/spl/spl-proc.o
In file included from /var/lib/dkms/spl/0.6.1/build/include/sys/kmem.h:38:0,
                 from /var/lib/dkms/spl/0.6.1/build/include/sys/kstat.h:32,
                 from /var/lib/dkms/spl/0.6.1/build/module/spl/../../module/spl/spl-proc.c:28:
/var/lib/dkms/spl/0.6.1/build/include/sys/vmsystm.h:77:8: error: redefinition of ‘struct vmalloc_info’
 struct vmalloc_info {
        ^
In file included from /usr/src/linux-headers-3.10.0-031000rc7-generic/arch/x86/include/asm/io.h:195:0,
                 from /usr/src/linux-headers-3.10.0-031000rc7-generic/arch/x86/include/asm/realmode.h:5,
                 from /usr/src/linux-headers-3.10.0-031000rc7-generic/arch/x86/include/asm/acpi.h:32,
                 from /usr/src/linux-headers-3.10.0-031000rc7-generic/arch/x86/include/asm/fixmap.h:19,
                 from /usr/src/linux-headers-3.10.0-031000rc7-generic/arch/x86/include/asm/apic.h:12,
                 from /usr/src/linux-headers-3.10.0-031000rc7-generic/arch/x86/include/asm/smp.h:13,
                 from /usr/src/linux-headers-3.10.0-031000rc7-generic/arch/x86/include/asm/mmzone_64.h:10,
                 from /usr/src/linux-headers-3.10.0-031000rc7-generic/arch/x86/include/asm/mmzone.h:4,
                 from include/linux/mmzone.h:919,
                 from include/linux/gfp.h:4,
                 from include/linux/kmod.h:22,
                 from include/linux/module.h:13,
                 from /var/lib/dkms/spl/0.6.1/build/include/sys/kstat.h:28,
                 from /var/lib/dkms/spl/0.6.1/build/module/spl/../../module/spl/spl-proc.c:28:
include/linux/vmalloc.h:173:8: note: originally defined here
 struct vmalloc_info {
        ^
/var/lib/dkms/spl/0.6.1/build/module/spl/../../module/spl/spl-proc.c: In function ‘proc_dir_entry_match’:
/var/lib/dkms/spl/0.6.1/build/module/spl/../../module/spl/spl-proc.c:1126:15: error: dereferencing pointer to incomplete type
         if (de->namelen != len)
               ^
/var/lib/dkms/spl/0.6.1/build/module/spl/../../module/spl/spl-proc.c:1129:32: error: dereferencing pointer to incomplete type
         return !memcmp(name, de->name, len);
                                ^
/var/lib/dkms/spl/0.6.1/build/module/spl/../../module/spl/spl-proc.c: In function ‘proc_dir_entry_find’:
/var/lib/dkms/spl/0.6.1/build/module/spl/../../module/spl/spl-proc.c:1137:16: error: dereferencing pointer to incomplete type
  for (de = root->subdir; de; de = de->next)
                ^
/var/lib/dkms/spl/0.6.1/build/module/spl/../../module/spl/spl-proc.c:1137:37: error: dereferencing pointer to incomplete type
  for (de = root->subdir; de; de = de->next)
                                     ^
/var/lib/dkms/spl/0.6.1/build/module/spl/../../module/spl/spl-proc.c: In function ‘proc_dir_entries’:
/var/lib/dkms/spl/0.6.1/build/module/spl/../../module/spl/spl-proc.c:1150:16: error: dereferencing pointer to incomplete type
  for (de = root->subdir; de; de = de->next)
                ^
/var/lib/dkms/spl/0.6.1/build/module/spl/../../module/spl/spl-proc.c:1150:37: error: dereferencing pointer to incomplete type
  for (de = root->subdir; de; de = de->next)
                                     ^
/var/lib/dkms/spl/0.6.1/build/module/spl/../../module/spl/spl-proc.c: In function ‘spl_proc_init’:
/var/lib/dkms/spl/0.6.1/build/module/spl/../../module/spl/spl-proc.c:1177:2: error: implicit declaration of function ‘create_proc_entry’ [-Werror=implicit-function-declaration]
  proc_spl_kmem_slab = create_proc_entry("slab", 0444, proc_spl_kmem);
  ^
/var/lib/dkms/spl/0.6.1/build/module/spl/../../module/spl/spl-proc.c:1177:21: warning: assignment makes pointer from integer without a cast [enabled by default]
  proc_spl_kmem_slab = create_proc_entry("slab", 0444, proc_spl_kmem);
                     ^
/var/lib/dkms/spl/0.6.1/build/module/spl/../../module/spl/spl-proc.c:1181:27: error: dereferencing pointer to incomplete type
         proc_spl_kmem_slab->proc_fops = &proc_slab_operations;
                           ^
/var/lib/dkms/spl/0.6.1/build/module/spl/../../module/spl/spl-proc.c: In function ‘proc_dir_entry_match’:
/var/lib/dkms/spl/0.6.1/build/module/spl/../../module/spl/spl-proc.c:1130:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
