### ISSUE TITLE
Won't build with kernel 3.6.2

### ISSUE THREAD

**Issue by FransUrbo** [openzfs/zfs#1052]
/usr/local/src/spl.turbo/module/spl/../../module/spl/spl-vnode.c: In function ‘vn_remove’:
/usr/local/src/spl.turbo/module/spl/../../module/spl/spl-vnode.c:454: error: implicit declaration of function ‘path_lookup’
make[5]: **\* [/usr/local/src/spl.turbo/module/spl/../../module/spl/spl-vnode.o] Error 1
make[4]: **\* [/usr/local/src/spl.turbo/module/spl] Error 2
