### ISSUE TITLE
ZFS kernel modul not building on CentOS Stream 8 on Kernel 4.18.0-383.el8.x86_64

### ISSUE THREAD

**Issue by Daniel-Nashed** [openzfs/zfs#13364]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| CentOS Stream
Distribution Version	|  8
Kernel Version	|  4.18.0-383.el8
Architecture	| x86_64
OpenZFS Version	| 2.0.6-1

### Describe the problem you're observing

Kernel module is not building after kernel update.
Reverting to previous kernel version also does not build the module any more.

I hope there is any work-around, because I can't load any ZFS file-system. 
And I am out of ideas to get the module build.

Any tip would be really appreciated. Only the kernel version changed.
I have one box left, I did not reboot, which still works.

### Describe how to reproduce the problem

Linux updated to current version which took me to kernel 4.18.0-383.el8.
Building the module automatically did not work.

I removed ZFS and and installed it again via:

```
yum erase zfs zfs-dkms libzfs2 spl spl-dkms libzpool2 -y
reboot
yum install zfs -y
``` 

### Include any warning/errors/backtraces from the system logs

The errors I found in the log:

```
Loading new zfs-2.0.6 DKMS files...
Deprecated feature: REMAKE_INITRD
Building for 4.18.0-383.el8.x86_64
Building initial module for 4.18.0-383.el8.x86_64
Deprecated feature: REMAKE_INITRD
Error! Bad return status for module build on kernel: 4.18.0-383.el8.x86_64 (x86_64)
Consult /var/lib/dkms/zfs/2.0.6/build/make.log for more information.
warning: %post(zfs-dkms-2.0.6-1.el8.noarch) scriptlet failed, exit status 10




/var/lib/dkms/zfs/2.0.6/build/include/os/linux/kernel/linux/simd_x86.h:346:9: error: implicit declaration of function ‘xgetbv’; did you mean ‘get_bh’? [-Werror=implicit-function-declaration]
  xcr0 = xgetbv(0);
         ^~~~~~
         get_bh
cc1: some warnings being treated as errors
  AS [M]  /var/lib/dkms/zfs/2.0.6/build/module/lua/setjmp/setjmp.o
make[5]: *** [scripts/Makefile.build:315: /var/lib/dkms/zfs/2.0.6/build/module/icp/algs/modes/gcm.o] Error 1
make[4]: *** [scripts/Makefile.build:556: /var/lib/dkms/zfs/2.0.6/build/module/icp] Error 2
make[4]: *** Waiting for unfinished jobs....
  LD [M]  /var/lib/dkms/zfs/2.0.6/build/module/lua/zlua.o
make[3]: *** [Makefile:1577: _module_/var/lib/dkms/zfs/2.0.6/build/module] Error 2
make[3]: Leaving directory '/usr/src/kernels/4.18.0-383.el8.x86_64'
make[2]: *** [Makefile:49: modules-Linux] Error 2
make[2]: Leaving directory '/var/lib/dkms/zfs/2.0.6/build/module'
make[1]: *** [Makefile:896: all-recursive] Error 1
make[1]: Leaving directory '/var/lib/dkms/zfs/2.0.6/build'
make: *** [Makefile:757: all] Error 2




```

**Comment by rincebrain** [comment]
You might have better luck with 2.0.7 or 2.1.4.

**Comment by Daniel-Nashed** [comment]
Looks like I was still on EL8.4 and uninstalled + replaced the repo:

```
yum remove zfs-release-1-8.4.noarch
dnf install https://zfsonlinux.org/epel/zfs-release.el8_5.noarch.rpm
```

I did not notice the machines have been all on the older version.
the newer repo has version 2.0.7. 

I will report back as soon the build is done and ZFS loads..

**Comment by Daniel-Nashed** [comment]
Works with newer repo. I was still on EL8.4 and had to switch to EL8.5.
Build and modprobe works in EL8.5. 

This is important to know. I thought the repo is updated to the latest. But there are different versions. 
I wasn't aware of that and it all worked fine with previous kernel updates.
