### ISSUE TITLE
zfs-0.6.0/include/sys/zio.h:431: error: expected specifier-qualifier-list before 'taskq_ent_t' with spl-0.6.0.rc10

### ISSUE THREAD

**Issue by tworks-pam** [openzfs/zfs#963]
When i try "make rpm", it ends up with this error. I have installed spl-.0.6.0.rc10. I can see in one other raised issues that it was fixed, but its not working with zfs-0.6.0. am i missting something?
