### ISSUE TITLE
New Packages required for CentOS 8.3

### ISSUE THREAD

**Issue by rearden888** [openzfs/zfs#11307]
### Describe the feature would like to see added to OpenZFS
New packages required now that CentOS has updated it's point release to 8.3.

I'm not sure if this happens automatically, or if this issue needs to be submitted, but now that CentOS upgraded to 8.3, I believe that a new package needs to be released for the current version.
### How will this feature improve OpenZFS?
Allow ZFS to be installed onto CentOS 8.3

### Additional context
Again, I'm not sure if this needs to be handled manually, but I don't think there is a package available to install kABI packages onto CentOS 8.3.  At least, I can't find a download link for that version at:
https://openzfs.github.io/openzfs-docs/Getting%20Started/RHEL%20and%20CentOS.html

**Comment by zorinlynx** [comment]
Compilation also fails if you're not using kABI packages.

Granted, 8.3 *JUST* came out, so I'm not really too salty about it, and you can always just keep running the previous kernel for the moment, but it does need to get fixed.

**Comment by tonyhutter** [comment]
Thanks for the heads-up, I'll roll some 0.8.5 packages for Centos 8.3.

**Comment by tonyhutter** [comment]
Centos 8.3 kernel interfaces changed :grimacing: :cry: 
```
  CC [M]  /builddir/build/BUILD/zfs-0.8.5/module/zfs/unique.o
  CC [M]  /builddir/build/BUILD/zfs-0.8.5/module/zfs/vdev.o
  CC [M]  /builddir/build/BUILD/zfs-0.8.5/module/zfs/vdev_cache.o
  CC [M]  /builddir/build/BUILD/zfs-0.8.5/module/zfs/vdev_disk.o
/builddir/build/BUILD/zfs-0.8.5/module/zfs/vdev_disk.c: In function 'vdev_bio_associate_blkg':
/builddir/build/BUILD/zfs-0.8.5/module/zfs/vdev_disk.c:530:22: error: implicit declaration of function 'vdev_blkg_tryget'; did you mean 'blkg_tryget'? [-Werror=implicit-function-declaration]
  if (q->root_blkg && vdev_blkg_tryget(q->root_blkg))
                      ^~~~~~~~~~~~~~~~
                      blkg_tryget
cc1: some warnings being treated as errors
```
RHEL 8.3 equivalent bug: https://github.com/openzfs/zfs/issues/11195

So it's not going to work without a patch.  It sounds like 2.0.0 works on Centos 8.3 though.

**Comment by rearden888** [comment]
I suppose there would be pushback on upgrading ZFS major versions to 2.0.0 within a CentOS release cycle.  Personally, I'm all for it, but I'm not sure how others would feel about it.  In the meantime, it might be worth a notice on the documentation that there aren't currently packages available for 8.3 if it's not a quick fix to build them.  

Is there an option to package up 2.0.0, for people who want to upgrade?  I don't really know how to do that, otherwise I'd try to help.

**Comment by gdevenyi** [comment]
#10333

**Comment by rearden888** [comment]
From reading that thread, doesn't it concern packaging for Debian/Ubuntu, not CentOS?

**Comment by IainCollins262** [comment]
> So it's not going to work without a patch. It sounds like 2.0.0 works on Centos 8.3 though.

Are there any plans for publishing an official 2.0.0 RPM for CentOS?

**Comment by imilne** [comment]
Is it safe to move from 0.8.x to 2.0.0? With existing zpools etc?

**Comment by rearden888** [comment]
I've upgraded several pools from 0.8.5 to 2.0.0 with no issues.  Admittedly, they are all pretty vanilla, mass storage volumes, but I haven't had any problems.  So, in my opinion, it is, but I don't have massive deployments or anything.  By releasing it as a full, stable version, my interpretation is that OpenZFS regards it that way, as well.

**Comment by imilne** [comment]
> I've upgraded several pools from 0.8.5 to 2.0.0 with no issues. Admittedly, they are all pretty vanilla, mass storage volumes, but I haven't had any problems. So, in my opinion, it is, but I don't have massive deployments or anything. By releasing it as a full, stable version, my interpretation is that OpenZFS regards it that way, as well.

Thanks, that's good to know. I'm currently trying to juggle a move to CentOS 8.3 for a system that relies on both ZFS and BeeGFS - both of which are suffering from these kernel changes. I can see us playing it safe and sticking with 8.2 until after the new year.

**Comment by zorinlynx** [comment]
>playing it safe and sticking with 8.2

Keep in mind that you can still upgrade to 8.3 and just continue running the previous kernel (4.18.0-193.28.1.el8_2.x86_64) until the ZFS update drops. This way you benefit from the other improvements in 8.3. 

This is what I've done for several servers I administrate and I haven't seen any issues.

**Comment by jrobersonaquent** [comment]
> Keep in mind that you can still upgrade to 8.3 and just continue running the previous kernel (4.18.0-193.28.1.el8_2.x86_64) until the ZFS update drops. This way you benefit from the other improvements in 8.3.
> 
> This is what I've done for several servers I administrate and I haven't seen any issues.

We just did this to our servers as well. We updated to 8.3 but set it to use the older kernel with `grubby --set-default /boot/vmlinuz-4.18.0-193.28.1.el8_2.x86_64`.

**Comment by ziggythehamster** [comment]
With 0.8.6 having just dropped, including [this repo](http://download.zfsonlinux.org/epel/zfs-release.el8_3.noarch.rpm), I think this issue is resolved, right?

**Comment by stuartthebruce** [comment]
Is a 2.0.1 release needed as well?
