### ISSUE TITLE
kmod-zfs fails to install for latest EL9.7 kernel

### ISSUE THREAD

**Issue by stuartthebruce** [openzfs/zfs#17987]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Rocky Linux
Distribution Version	| 9.7-RC2
Kernel Version	|  5.14.0-611.9.1.el9_7
Architecture	| x86_64
OpenZFS Version	| 2.3.5

### Describe the problem you're observing

Attempting to install **kmod-zfs-2.3.5-1.el9.x86_64.rpm** from http://download.zfsonlinux.org/epel-testing/9.7/kmod/x86_64/ fails to install a kernel module for the latest 9.7 kernel, though it does install for an older 9.7 kernel. Perhaps a new build for EL9.7 is needed?

### Describe how to reproduce the problem

<pre>
[root@ldas-pcdev15 ~]# cat /etc/redhat-release 
Rocky Linux release 9.7 (Blue Onyx)

[root@ldas-pcdev15 ~]# uname -r
5.14.0-611.9.1.el9_7.x86_64

[root@ldas-pcdev15 ~]# rpm -q kernel-core
kernel-core-5.14.0-611.9.1.el9_7.x86_64

[root@ldas-pcdev15 ~]# dnf --enablerepo=zfs-testing-kmod install zfs
Last metadata expiration check: 0:01:02 ago on Thu 27 Nov 2025 02:30:34 PM PST.
Dependencies resolved.
==========================================================================================
 Package                 Arch       Version                    Repository            Size
==========================================================================================
Installing:
 kernel-core             x86_64     5.14.0-611.5.1.el9_7       baseos                17 M
 kernel-modules-core     x86_64     5.14.0-611.5.1.el9_7       baseos                31 M
 zfs                     x86_64     2.3.5-1.el9                zfs-testing-kmod     754 k
Installing dependencies:
 kmod-zfs                x86_64     2.3.5-1.el9                zfs-testing-kmod     1.7 M
 libnvpair3              x86_64     2.3.5-1.el9                zfs-testing-kmod      37 k
 libuutil3               x86_64     2.3.5-1.el9                zfs-testing-kmod      30 k
 libzfs6                 x86_64     2.3.5-1.el9                zfs-testing-kmod     223 k
 libzpool6               x86_64     2.3.5-1.el9                zfs-testing-kmod     1.3 M

Transaction Summary
==========================================================================================
Install  8 Packages

Total download size: 52 M
Installed size: 116 M
Is this ok [y/N]: 
Operation aborted.
</pre>

Note, **dnf** installing an older version of **kernel-core**. I am able to get this version of **kmod-zfs-2.3.5** to install and work with that older kernel. And I am also able to get **zfs-dkms-2.3.5** to work with the latest kernel. However, it would be nice to be able to use **kmod-zfs** with the latest kernel

P.S. This was discovered with Rocky Linux 9.7 RC2. So if nobody beats me to it by reproducing on RHEL 9.7 with [RHSA-2025:21926 - Security Advisory](https://access.redhat.com/errata/RHSA-2025:21926) then I will reproduce with RL9.7 GA when that comes out early next week, or send an apology if this is somehow subtly related to the near final RL9.7 RC2 and is resolved in RL9.7 GA.

P.P.S. If someone updates the EL9.7 repo please also take a look at updating the EL10.1 repo for #17966 

### Include any warning/errors/backtraces from the system logs

None. Presumably **dnf** is looking for kernel symbols and finding them only in the older kernel.

**Comment by stuartthebruce** [comment]
Sorry for the noise. I do not see the problematic `kernel-5.14.0-611.9.1.el9_7` in the final Rocky Linux 9.7 GA release bits hitting the mirrors this weekend. However, I will leave this open until that security update shows up in either AlmaLinux or Rocky Linux GA to confirm there isn't a problem. Note, if anyone is running the RHEL9.7 where this is already available that would be nice to check as well.

**Comment by PeterFalken** [comment]
@stuartthebruce - I did a NAS test build with Alma 9.7 and deploying `kmod-2.3.5` seemed to work for me. Your mileage may vary.
```
dnf install -y \
    https://zfsonlinux.org/epel/zfs-release-3-0$(rpm --eval "%{dist}").noarch.rpm
dnf config-manager --disable zfs
dnf config-manager --enable zfs-2.3-kmod
dnf install -y zfs
```

**Comment by stuartthebruce** [comment]
> I did a NAS test build with Alma 9.7 and deploying `kmod-2.3.5` seemed to work for me.

Which kernel?

**Comment by PeterFalken** [comment]
> Which kernel?

It might be an older one.
```
[clerk@tnas ~]$ uname -a
Linux tnas.lan 5.14.0-611.5.1.el9_7.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Nov 11 08:09:09 EST 2025 x86_64 x86_64 x86_64 GNU/Linux
```

```
[clerk@tnas ~]$ cat /etc/os-release 
NAME="AlmaLinux"
VERSION="9.7 (Moss Jungle Cat)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.7"
PLATFORM_ID="platform:el9"
PRETTY_NAME="AlmaLinux 9.7 (Moss Jungle Cat)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.7"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.7"
SUPPORT_END=2032-06-01
[clerk@tnas ~]$ zfs version
zfs-2.3.5-1
zfs-kmod-2.3.5-1
```

**Comment by stuartthebruce** [comment]
> it might be an older one.

I am interested to see what happens when Alma Linux releases **kernel-5.14.0-611.9.1.el9_7** (or newer)

**Comment by hollow** [comment]
Kernel 5.14.0-611.9.1.el9_7.x86_64 is now released and upgraded systems break ZFS as per usual :(

**Comment by stuartthebruce** [comment]
Here is hoping that RH was already aware of a possible leaked kernel ABI change and fixed that as part of the even newer [kernel-5.14.0-611.11.1.el9_7.x86_64](https://access.redhat.com/errata/RHSA-2025:22405) released today. However, I don't have a bona fide RHEL 9.7 system to test on.

**Comment by jb-alvarado** [comment]
Same is happen with `zfs-2.2.9-1.el9`.

**Comment by tmzullinger** [comment]
I have a RHEL 9 VM for testing and (after fighting the usual fight to make their awful subscription manager work after a few months of inactivity) I was able to confirm that the latest kernel (`11.1`) there doesn't revert the changes which make the `9.1` kernel require yet another kmod rebuild. :(

Apparently, they changed the ABI just after the initial 9.7 kernel (`5.14.0-611.5.1.el9_7`).

**Comment by AadityaGala** [comment]
Decided to migrate from Rocky Linux 8 to Rocky Linux 9. Did not know that v9.7 was released just yesterday. Get the following error when trying to run `sudo dkms autoinstall`
```
Autoinstall of module zfs/2.2.7 for kernel 5.14.0-611.9.1.el9_7.x86_64 (x86_64)
Running the pre_build script........... done.
Building module(s)..........(bad exit status: 2)
Failed command:
make -j16 KERNELRELEASE=5.14.0-611.9.1.el9_7.x86_64

Error! Bad return status for module build on kernel: 5.14.0-611.9.1.el9_7.x86_64 (x86_64)
Consult /var/lib/dkms/zfs/2.2.7/build/make.log for more information.

Autoinstall on 5.14.0-611.9.1.el9_7.x86_64 failed for module(s) zfs(10).

Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
```

`cat`ting the log file:
```
/var/lib/dkms/zfs/2.2.7/build/module/os/linux/zfs/zvol_os.c: In function ‘zvol_blk_mq_alloc_tag_set’:
/var/lib/dkms/zfs/2.2.7/build/module/os/linux/zfs/zvol_os.c:205:30: error: ‘BLK_MQ_F_SHOULD_MERGE’ undeclared (first use in this function)
  205 |         zso->tag_set.flags = BLK_MQ_F_SHOULD_MERGE | BLK_MQ_F_BLOCKING;
         |                              ^~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/zfs/2.2.7/build/module/os/linux/zfs/zvol_os.c:205:30: note: each undeclared identifier is reported only once for each function it appears in
```

EDIT:
Did run ` sudo dnf install https://zfsonlinux.org/epel/zfs-release-3-0$(rpm --eval "%{dist}").noarch.rpm` before.

**Comment by AadityaGala** [comment]
UPDATE:
The `45Drive Enterprise` repo was causing a conflict and so I was installing an older version. Disabling the repo and reinstalling zfs, installed v2.3.5. `sudo dkms autoinstall` now works without any issues. But `sudo modprobe zfs` reports the following error:
```
modprobe: FATAL: Module zfs not found in directory /lib/modules/5.14.0-611.9.1.el9_7.x86_64
```

**Comment by tmzullinger** [comment]
> UPDATE: The `45Drive Enterprise` repo was causing a conflict and so I was installing an older version. Disabling the repo and reinstalling zfs, installed v2.3.5. `sudo dkms autoinstall` now works without any issues. But `sudo modprobe zfs` reports the following error:

@AadityaGala, it's probably better to file a new issue for problems with the dkms module build.  This issue is about the pre-built kmod-zfs packaging of the zfs kernel module for EL9.7.

**Comment by baileyallison** [comment]
> UPDATE: The `45Drive Enterprise` repo was causing a conflict and so I was installing an older version. Disabling the repo and reinstalling zfs, installed v2.3.5. `sudo dkms autoinstall` now works without any issues. But `sudo modprobe zfs` reports the following error:
> 
> ```
> modprobe: FATAL: Module zfs not found in directory /lib/modules/5.14.0-611.9.1.el9_7.x86_64
> ```

@AadityaGala our bad, we are looking into this now :(

**Comment by tonyhutter** [comment]
I'm seeing the same kmod failure when updating from 5.14.0-503.40.1.el9_5 -> 5.14.0-611.9.1.el9_7.  I will rebuild the kmods.  Assigning issue to myself.

**Comment by stuartthebruce** [comment]
@tonyhutter what do you think about automating testing for upstream EL kernel KABI breakage? Perhaps a CI job that loads/tests kmod rpm on CentOS Stream, or even just a test against bona fide RHEL to find these issues earlier than when they show up in Rocky Linux, AlmaLinux and friends?

**Comment by tonyhutter** [comment]
@stuartthebruce I'm fine with that idea.  I'm not sure where you could get non-paywalled RHEL qcow2 images for the CI to use though (see https://github.com/openzfs/zfs/blob/master/.github/workflows/scripts/qemu-2-start.sh).  PRs welcome!

**Comment by tonyhutter** [comment]
New kmods uploaded - please try it again.  Sometimes you have to do a `dnf clean all` first to get it to work immediately.

**Comment by stuartthebruce** [comment]
> New kmods uploaded - please try it again.

Works for me.
