### ISSUE TITLE
ZFS 2.1.12 + Kernel 6.3.x

### ISSUE THREAD

**Issue by Lisio** [openzfs/zfs#15021]
### System information
Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 23.04
Kernel Version	| 6.2.12
Architecture	| x86_64
OpenZFS Version	| zfs-2.1.9-2ubuntu1.1, zfs-kmod-2.1.11-1

### Describe the problem you're observing
Unsupported kernel 6.3.10

### Describe how to reproduce the problem
```
make -j54 bindeb-pkg
```

### Include any warning/errors/backtraces from the system logs
```
In file included from ./include/zfs/os/linux/zfs/sys/policy.h:36,
                 from fs/zfs/zfs/dmu_objset.c:62:
./include/zfs/os/linux/zfs/sys/zpl.h:197:2: error: #error "Unsupported kernel"
  197 | #error "Unsupported kernel"
      |  ^~~~~
```

Kernel .config file:
[.config](https://github.com/openzfs/zfs/files/11915720/config.txt)

**Comment by rincebrain** [comment]
Since this compiles on 6.3.x for me, you're going to need to include all the details in the template that you deleted for anyone to help.

**Comment by Lisio** [comment]
Updated with details and attached my custom kernel config file which I used to build my current 6.2.12+2.1.11 system.

**Comment by Lisio** [comment]
I think the reason for this error is that I did git checkout with make clean but without running autogen.sh, so configure script was left from previos version of zfs. Making all the steps from clean dir solved the issue and 3.6.11 compiled successfully.
