### PR TITLE
Fix multiple definitions of struct mount_attr on recent glibc versions

### LINKED ISSUE #14057: Building master is broken by 2a068a1394d179dda4becf350e3afb4e8819675e
### System information

Type | Version/Name
 --- | ---
Distribution Name	|Gentoo
Distribution Version	|2.9
Kernel Version	|5.16.14-gentoo-x86_64
Architecture	|x86_64
OpenZFS Version	|master

### Describe the problem you're observing
Building master fails with:
```
tests/zfs-tests/cmd/idmap_util.c:103:8: error: redefinition of ‘struct mount_attr’
  103 | struct mount_attr {
      |        ^~~~~~~~~~
In file included from /usr/include/sys/mount.h:32,
                 from ./lib/libspl/include/os/linux/sys/mount.h:27,
                 from ./lib/libspl/include/os/linux/sys/stat.h:31,
                 from tests/zfs-tests/cmd/idmap_util.c:33:
/usr/include/linux/mount.h:129:8: note: originally defined here
  129 | struct mount_attr {
      |        ^~~~~~~~~~
```
### Describe how to reproduce the problem
```
git clone https://github.com/openzfs/zfs.git
cd zfs
git clean -xdf && ./autogen.sh && ./configure --enable-debug --enable-debuginfo --with-config=all && make -j$(nproc)
```

2a068a1394d179dda4becf350e3afb4e8819675e introduced this code.

The problem code is:
```
#ifndef mount_attr
struct mount_attr {
        __u64 attr_set;
        __u64 attr_clr;
        __u64 propagation;
        __u64 userns_fd;
};
#endif
```
I am not sure how this was expected to work in the first place. You cannot use the CPP to check what C structures are defined. An autotools check is needed for that.

### PR DESCRIPTION
**Pull request by ryao**
The ifdef used would never work because the CPP is not aware of C structure definitions. Rather than use an autotools check, we can just use a nameless structure that we typedef to mount_attr_t. This is a Linux kernel interface, which means that it is stable and this is fine to do.

Closes #14057

### CODE REVIEW

**Comment by behlendorf** [comment]
@youzhongyang would you mind take a look at this.

**Comment by youzhongyang** [comment]
Thanks. It looks good to me.

**Review by behlendorf — APPROVED** [review]
