### ISSUE TITLE
Linux 5.8 build error

### ISSUE THREAD

**Issue by cheesycod** [openzfs/zfs#10533]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Fedora (I know it is not supported, just wanted to put up this issue so it can be fixed before linux 5.8 is released
Distribution Version	| Rawhide
Linux Kernel	| 5.8
Architecture	| x86_64
ZFS Version	| latest master (0.8.0 according to dkms)
SPL Version	| NA

### Describe the problem you're observing
```make[3]: Entering directory '/usr/src/kernels/5.8.0-0.rc3.20200701git7c30b859a947.1.fc33.x86_64'
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/avl/avl.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/spl/../os/linux/spl/spl-atomic.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/lua/lapi.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/icp/illumos-crypto.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/spl/../os/linux/spl/spl-condvar.o
  LD [M]  /var/lib/dkms/zfs/0.8.0/build/module/avl/zavl.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/icp/api/kcf_cipher.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/icp/api/kcf_digest.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/spl/../os/linux/spl/spl-cred.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/lua/lauxlib.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/spl/../os/linux/spl/spl-err.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/icp/api/kcf_mac.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/icp/api/kcf_miscapi.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/spl/../os/linux/spl/spl-generic.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/lua/lbaselib.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/icp/api/kcf_ctxops.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/icp/core/kcf_callprov.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/spl/../os/linux/spl/spl-kmem.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/lua/lcode.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/icp/core/kcf_prov_tabs.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/spl/../os/linux/spl/spl-kmem-cache.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/icp/core/kcf_sched.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/lua/lcompat.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/icp/core/kcf_mech_tabs.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/spl/../os/linux/spl/spl-kstat.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/lua/lcorolib.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/icp/core/kcf_prov_lib.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/icp/spi/kcf_spi.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/spl/../os/linux/spl/spl-proc.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/lua/lctype.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/icp/io/aes.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/spl/../os/linux/spl/spl-procfs-list.o
In file included from ./include/linux/spinlock_types.h:18,
                 from ./include/linux/mutex.h:16,
                 from /var/lib/dkms/zfs/0.8.0/build/include/os/linux/spl/sys/mutex.h:29,
                 from /var/lib/dkms/zfs/0.8.0/build/module/spl/../os/linux/spl/spl-procfs-list.c:26:
/var/lib/dkms/zfs/0.8.0/build/include/os/linux/spl/sys/mutex.h: In function ‘spl_mutex_lockdep_off_maybe’:
./include/linux/lockdep.h:325:9: error: invalid use of undefined type ‘struct task_struct’
  325 |  current->lockdep_recursion += LOCKDEP_OFF; \
      |         ^~
/var/lib/dkms/zfs/0.8.0/build/include/os/linux/spl/sys/mutex.h:78:3: note: in expansion of macro ‘lockdep_off’
   78 |   lockdep_off();     \
      |   ^~~~~~~~~~~
/var/lib/dkms/zfs/0.8.0/build/include/os/linux/spl/sys/mutex.h: In function ‘spl_mutex_lockdep_on_maybe’:
./include/linux/lockdep.h:330:9: error: invalid use of undefined type ‘struct task_struct’
  330 |  current->lockdep_recursion -= LOCKDEP_OFF; \
      |         ^~
/var/lib/dkms/zfs/0.8.0/build/include/os/linux/spl/sys/mutex.h:84:3: note: in expansion of macro ‘lockdep_on’
   84 |   lockdep_on();     \
      |   ^~~~~~~~~~
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/lua/ldebug.o
  CC [M]  /var/lib/dkms/zfs/0.8.0/build/module/icp/io/edonr_mod.o
make[5]: *** [scripts/Makefile.build:281: /var/lib/dkms/zfs/0.8.0/build/module/spl/../os/linux/spl/spl-procfs-list.o] Error 1
make[4]: *** [scripts/Makefile.build:497: /var/lib/dkms/zfs/0.8.0/build/module/spl] Error 2```

### Describe how to reproduce the problem
Try building the ZFS kmod on linux 5.8-rc3
### Include any warning/errors/backtraces from the system logs
<!--
*IMPORTANT* - Please mark logs and text output from terminal commands
or else Github will not display them correctly.
An example is provided below.

Example:
```
this is an example how log text should be marked (wrap it with ```)
```
-->

**Comment by cheesycod** [comment]
After manually modifying lockdep.h to return always (hacky solution), it compiles. However, we should automatically fail if lockdep is being used

**Comment by Atemu** [comment]
ZFS 0.8.4 compiles and works with linux-zen 5.8 on Nix/NixOS. We have backported https://github.com/openzfs/zfs/pull/10422 but that should only affect vmalloc.

**Comment by mnd999** [comment]
On Arch on a 5.8 kernel I get:
```
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/zcommon/zfs_fletcher_superscalar4.o
/var/lib/dkms/zfs/0.8.4/build/module/spl/spl-kmem.c: In function ‘spl_kmem_alloc_impl’:
/var/lib/dkms/zfs/0.8.4/build/module/spl/spl-kmem.c:183:11: error: too many arguments to function ‘__vmalloc’
  183 |     ptr = __vmalloc(size, lflags | __GFP_HIGHMEM,
      |           ^~~~~~~~~
In file included from /var/lib/dkms/zfs/0.8.4/build/include/spl/sys/vmem.h:30,
                 from /var/lib/dkms/zfs/0.8.4/build/module/spl/spl-kmem.c:28:
./include/linux/vmalloc.h:111:14: note: declared here
  111 | extern void *__vmalloc(unsigned long size, gfp_t gfp_mask);
      |              ^~~~~~~~~
make[5]: *** [scripts/Makefile.build:281: /var/lib/dkms/zfs/0.8.4/build/module/spl/spl-kmem.o] Error 1
make[5]: *** Waiting for unfinished jobs....
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/zcommon/zfs_namecheck.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/zcommon/zfs_prop.o
/var/lib/dkms/zfs/0.8.4/build/module/spl/spl-kmem-cache.c: In function ‘kv_alloc’:
/var/lib/dkms/zfs/0.8.4/build/module/spl/spl-kmem-cache.c:206:9: error: too many arguments to function ‘__vmalloc’
  206 |   ptr = __vmalloc(size, lflags | __GFP_HIGHMEM, PAGE_KERNEL);
      |         ^~~~~~~~~
In file included from /var/lib/dkms/zfs/0.8.4/build/include/spl/sys/vmem.h:30,
                 from /var/lib/dkms/zfs/0.8.4/build/module/spl/spl-kmem-cache.c:30:
./include/linux/vmalloc.h:111:14: note: declared here
  111 | extern void *__vmalloc(unsigned long size, gfp_t gfp_mask);
      |              ^~~~~~~~~
make[5]: *** [scripts/Makefile.build:281: /var/lib/dkms/zfs/0.8.4/build/module/spl/spl-kmem-cache.o] Error 1
make[4]: *** [scripts/Makefile.build:497: /var/lib/dkms/zfs/0.8.4/build/module/spl] Error 2
make[4]: *** Waiting for unfinished jobs....
```

**Comment by Atemu** [comment]
That smells like the vmalloc incompat fixed in the PR I mentioned, try applying https://patch-diff.githubusercontent.com/raw/openzfs/zfs/pull/10422.patch to ZFS.

**Comment by svde** [comment]
Fedora just updated the kernel package to 5.8.4-200.fc32

**Comment by behlendorf** [comment]
Closing.  These compatibility fixes are part of the supported releases.
