### ISSUE TITLE
OpenZFS 2.2.7 doest not compile with Linux 6.14-rc1

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [openzfs/zfs#17025]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Proxmox + [custom kernel](https://github.com/KrzysztofHajdamowicz/pve-kernel)
Distribution Version	| 8
Kernel Version	| 6.14-rc1
Architecture	| x86_64
OpenZFS Version	| 2.2.7

### Describe the problem you're observing

OpenZFS 2.2.7 does not compile with kernel 6.14-rc1
```
  CC [M]  os/linux/zfs/zpl_file_range.o
os/linux/zfs/zpl_ctldir.c:204:27: error: initialization of 'int (*)(struct inode *, const struct qstr *, struct dentry *, unsigned int)' from incompatible pointer type 'int (*)(struct dentry *, unsigned int)' [-Werror=incompatible-pointer-types]
  204 |         .d_revalidate   = zpl_snapdir_revalidate,
      |                           ^~~~~~~~~~~~~~~~~~~~~~
os/linux/zfs/zpl_ctldir.c:204:27: note: (near initialization for 'zpl_dops_snapdirs.d_revalidate')
```

### Describe how to reproduce the problem

Issue appears when compiling kernel 6.14- there was no issue with kernel 6.13.

To try it at your own:

1. Grab pve-kernel repo https://github.com/KrzysztofHajdamowicz/pve-kernel
2. `git submodule init && git submodule update`
3. `cd submodules/ubuntu-kernel && git remote add github https://github.com/KrzysztofHajdamowicz/mirror_ubuntu-kernels.git`
4. `cd submodules/ubuntu-kernel && git checkout github/build`
5.  Use https://github.com/KrzysztofHajdamowicz/pve-kernel-zfsonlinux as submodules/zfsonlinux (note `upstream` submodule that point to openzfs/zfs repo)
6. `make`
7. Result is: [build.txt](https://github.com/user-attachments/files/18661922/build.txt)

6.14 (and even 6.13) is too new to be mentioned as supported in release notes but FIY some code changes will be needed in the future 🙂

**Comment by KrzysztofHajdamowicz** [comment]
I've cherry-picked those commits, kernel compiled and booted from rootfs on ZFS. Works for me, thanks!

**Comment by KrzysztofHajdamowicz** [comment]
I can confirm that patchet from #17026 works for all 6.14 versions up to v6.14 git tag in Linus repo.

**Comment by dylandn** [comment]
I appear to be hitting this same issue with 2.3.2 on kernel 6.12.28

**Comment by dylandn** [comment]
Nevermind. User error. I used the copy_builtin.sh script to add zfs to both 2.12 and 2.14 kernels and it feels like if you apply it to a 2.14 kernel first then to a 2.12 kernel later, zfs_config.h and HAVE_D_REVALIDATE_4ARGS doesn't get refreshed.
