### ISSUE TITLE
Building head on 3.11.6 (openSUSE 13.1): linux/delay_compat.h nonexistent

### ISSUE THREAD

**Issue by slburson** [openzfs/zfs#2130]
Hi,

I just cloned the current head and tried to build on 3.11.6 (openSUSE 13.1), and got:

```
  CC [M]  /FTP/Linux/ZFS/zfs-git/module/zcommon/../../module/zcommon/zfs_deleg.o
In file included from /FTP/Linux/ZFS/zfs-git/include/sys/zfs_context.h:64:0,
                 from /FTP/Linux/ZFS/zfs-git/include/sys/spa.h:31,
                 from /FTP/Linux/ZFS/zfs-git/include/sys/dsl_pool.h:29,
                 from /FTP/Linux/ZFS/zfs-git/include/sys/dsl_deleg.h:30,
                 from /FTP/Linux/ZFS/zfs-git/module/zcommon/../../module/zcommon/zfs_deleg.c:38:
/FTP/Linux/ZFS/zfs-git/include/sys/zfs_delay.h:25:32: fatal error: linux/delay_compat.h: No such file or directory
```

I don't actually care about this -- I'm running 0.6.2, which doesn't have this problem, and was building the current head just to get the new systemd unit files -- but I thought you might want to know.
