### ISSUE TITLE
make rpm is using host libraries

### ISSUE THREAD

**Issue by dechamps** [openzfs/zfs#909]
Note: previous title was "make rpm: undefined reference to zfs_prop_written".

With latest git master, on Debian squeeze, `make rpm` fails:

```
$ ./autogen.sh && ./configure --enable-debug --with-config=user && make rpm
[...]
/bin/bash ../../libtool  --tag=CC --silent  --mode=link gcc -Wall -Wstrict-prototypes -fno-strict-aliasing  -DNDEBUG -D_GNU_SOURCE -D__EXTENSIONS__ -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DTEXT_DOMAIN=\"zfs-linux-user\" -O2 -g -pthread -lm -lz -lrt -ldl -luuid  -lselinux  -o mount.zfs mount_zfs.o ../../lib/libuutil/libuutil.la ../../lib/libzfs/libzfs.la -luuid -luuid -lz -lz -lz 
../../lib/libzfs/.libs/libzfs.so: undefined reference to `zfs_prop_written'
collect2: ld returned 1 exit status
make[5]: *** [mount.zfs] Error 1
make[5]: Leaving directory `/tmp/zfs-build-root-CeEUXRma/BUILD/zfs-0.6.0/cmd/mount_zfs'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory `/tmp/zfs-build-root-CeEUXRma/BUILD/zfs-0.6.0/cmd'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/tmp/zfs-build-root-CeEUXRma/BUILD/zfs-0.6.0'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/tmp/zfs-build-root-CeEUXRma/BUILD/zfs-0.6.0'
error: Bad exit status from /tmp/zfs-build-root-CeEUXRma/TMP/rpm-tmp.yPK0gX (%build)
```

Note that, surprisingly, normal `make` (without `rpm`) works.

A bissection indicates the issue is caused by ca8b5af89d2c5826af7385bf18f3b377b0efde11.
