### ISSUE TITLE
Build fails on kernel version 5.4 and above.

### ISSUE THREAD

**Issue by pgwipeout** [openzfs/zfs#9842]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  Ubuntu Eoan 
Distribution Version	|  19.10
Linux Kernel	|  5.4.11
Architecture	|  aarch64
ZFS Version	|  0.8.1 
SPL Version	| 

### Describe the problem you're observing
zfs_dkms package fails to build due to kernel changes introduced in v5.4-rc1.
```
commit ce6595a28a15c874aee374757dcd08f537d7b24d
Author: Al Viro <viro@zeniv.linux.org.uk>
Date:   Sun Jul 14 16:42:44 2019 -0400

    kill the last users of user_{path,lpath,path_dir}()

    old wrappers with few callers remaining; put them out of their misery...

    Signed-off-by: Al Viro <viro@zeniv.linux.org.uk>
```
Removed `user_path_dir` from include/linux/namei.h
This breaks building of spl, as spl-vnode.c uses this function.

### Describe how to reproduce the problem

Attempt to install zfs_dkms on Ubuntu Eoan running a v5.4 or above kernel.

### Include any warning/errors/backtraces from the system logs

```
Unpacking zfs-dkms (0.8.1-1ubuntu14.3) ...
Setting up zfs-dkms (0.8.1-1ubuntu14.3) ...
Loading new zfs-0.8.1 DKMS files...
Building for 5.4.11-00006-g887426577d1c
Building initial module for 5.4.11-00006-g887426577d1c
Error! Bad return status for module build on kernel: 5.4.11-00006-g887426577d1c (aarch64)
Consult /var/lib/dkms/zfs/0.8.1/build/make.log for more information.
dpkg: error processing package zfs-dkms (--configure):
 installed zfs-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 zfs-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
```
CC [M]  /var/lib/dkms/zfs/0.8.1/build/module/zfs/cityhash.o
/var/lib/dkms/zfs/0.8.1/build/module/spl/spl-vnode.c: In function ‘vn_set_pwd’:
/var/lib/dkms/zfs/0.8.1/build/module/spl/spl-vnode.c:683:7: error: implicit declaration of function ‘user_path_dir’; did you mean ‘user_path_at’? [-Werror=implicit-function-declaration]
  683 |  rc = user_path_dir(filename, &path);
      |       ^~~~~~~~~~~~~
      |       user_path_at
  CC [M]  /var/lib/dkms/zfs/0.8.1/build/module/zfs/dbuf.o
cc1: some warnings being treated as errors
  CC [M]  /var/lib/dkms/zfs/0.8.1/build/module/zfs/dbuf_stats.o
make[5]: *** [scripts/Makefile.build:265: /var/lib/dkms/zfs/0.8.1/build/module/spl/spl-vnode.o] Error 1
make[4]: *** [scripts/Makefile.build:509: /var/lib/dkms/zfs/0.8.1/build/module/spl] Error 2
make[4]: *** Waiting for unfinished jobs....
```

Reference: https://github.com/zfsonlinux/spl/issues/719

**Comment by behlendorf** [comment]
The fix for this issue was included in the 0.8.2 tag.  Commit 328c95e removed the calls to `user_path_dir`.

**Comment by pgwipeout** [comment]
I implemented my own fix to the dkms module source by changing the offending line to:
```
rc = user_path_at(AT_FDCWD, filename,
                             LOOKUP_FOLLOW | LOOKUP_DIRECTORY, &path);
``` 
similar to the changes implemented in the breaking commit.

However I'm running into another issue:
```
 LD [M]  /var/lib/dkms/zfs/0.8.1/build/module/zfs/zfs.o
  Building modules, stage 2.
  MODPOST 8 modules
FATAL: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'preempt_schedule_notrace'
make[4]: *** [scripts/Makefile.modpost:94: __modpost] Error 1
make[3]: *** [Makefile:1609: modules] Error 2
make[3]: Leaving directory '/home/master/build2/linux-next'
make[2]: *** [Makefile:30: modules] Error 2
make[2]: Leaving directory '/var/lib/dkms/zfs/0.8.1/build/module'
make[1]: *** [Makefile:807: all-recursive] Error 1
make[1]: Leaving directory '/var/lib/dkms/zfs/0.8.1/build'
make: *** [Makefile:676: all] Error 2
```

I am also encountering this issue when I tried building the git master tree, currently on 5.4.11:
```
LD [M]  /home/master/build2/zfs/module/zfs/zfs.o
  Building modules, stage 2.
  MODPOST 8 modules
FATAL: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'preempt_schedule_notrace'
make[4]: *** [scripts/Makefile.modpost:94: __modpost] Error 1
make[3]: *** [Makefile:1609: modules] Error 2
make[3]: Leaving directory '/home/master/build2/linux-next'
make[2]: *** [Makefile:39: modules-Linux] Error 2
make[2]: Leaving directory '/home/master/build2/zfs/module'
make[1]: *** [Makefile:841: all-recursive] Error 1
make[1]: Leaving directory '/home/master/build2/zfs'
make: *** [Makefile:702: all] Error 2
```

**Comment by behlendorf** [comment]
Closing.  This issue was resolved in all release branches and master.
