### PR TITLE
[2.2.8] various Linux kernel updates

### PR DESCRIPTION
**Pull request by robn**
### Motivation and Context

Bring some Linux kernel version updates and bugfixes back to the 2.2 branch.

### Description

Includes:
- #17298 
- #17026 
- #17131 
- #17121 
- #16723
- #17217

### How Has This Been Tested?

Compile checked latest release of all LTS kernels back to 4.19, and all 6.x kernels.

Also compile checked on FreeBSD 14.2.

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by robn** [comment]
@tonyhutter I dunno if a 2.2.8 is planned (probably entirely dependent on demand). If it does happen, I'm very happy to assist with testing to get it out the door.

**Review by amotin — APPROVED** [review]

**Comment by tonyhutter** [comment]
I tried this on Fedora 42 (6.14 kernel) and wasn't able to get it to build.  Pulling in 155847c72dd91117887b85f54ef006f7690c38de helped, but then I hit:
```
make[2]: Entering directory '/home/hutter/zfs'
  CC       module/zfs/libzpool_la-ddt.lo
module/zfs/ddt.c: In function 'ddt_stat_update':
module/zfs/ddt.c:445:9: error: array subscript -1 is below array bounds of 'ddt_stat_t[64]' {aka 'struct ddt_stat[64]'} [-Werror=array-bounds=]
  445 |         ddt_stat_add(&ddh->ddh_stat[bucket], &dds, neg);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./include/sys/spa.h:44,
                 from module/zfs/ddt.c:29:
./include/sys/fs/zfs.h:1331:25: note: while referencing 'ddh_stat'
 1331 |         ddt_stat_t      ddh_stat[64];   /* power-of-two histogram buckets */
      |                         ^~~~~~~~
cc1: all warnings being treated as errors
```

**Comment by amotin** [comment]
It seems #17334 would be good too.  Though it is not in 2.3 yet.

**Review by behlendorf — APPROVED** [review]

**Comment by lzsaver** [comment]
#17340 and #17343 look important. Both build well on top of 2.2.7.

**Comment by behlendorf** [comment]
These are all now in master https://github.com/openzfs/zfs/pull/17334, https://github.com/openzfs/zfs/pull/17340 and https://github.com/openzfs/zfs/pull/17343 and would be good to include in a 2.2.8 release.

**Comment by ryao** [comment]
We might as well include #17353 once it is merged.

**Comment by shodanshok** [comment]
What about https://github.com/openzfs/zfs/pull/17255 ?

For what it is worth, I welcome a 2.2.8 release - maybe even as the new default/stable branch for EL 9 (which is at 2.1.16 actually).

**Comment by robn** [comment]
All suggestions included, top posted updated. Looks like we're putting a release together!

I went back through the ~600 commits on master that aren't on the 2.2 series, and there's a good amount of fixes for leaks, overflows, null derefs and so on. I didn't really want to load up 2.2 this late though, feels like we should be very sparing with on the LTS branch.

Anyway, feel free to nominate stuff I guess :)

**Review by amotin — APPROVED** [review]

**Comment by aerusso** [comment]
Could you include 8bf1e83eefa4f4ed74505f4a9ba4c3720c73185c please too?  It fixes some ZTS failures on Debian.
