### ISSUE TITLE
master branch does not build on 3.13 kernel

### ISSUE THREAD

**Issue by alexclear** [openzfs/zfs#2311]
I'm using Fedora 19 i686 w/kernel 3.13.11-100.fc19.i686.PAE

I tried to build a DKMS ZFS module off a HEAD of a master branch (2c33b9127569ad62b4cfe7dd4f651ceeee3d005c at the time of writing) but got the following error:

```
  CC [M]  /var/lib/dkms/zfs/0.6.2/build/module/zfs/../../module/zfs/dmu.o
In file included from include/linux/blkdev.h:18:0,
                 from /var/lib/dkms/zfs/0.6.2/build/include/linux/blkdev_compat.h:32,
                 from /var/lib/dkms/zfs/0.6.2/build/include/sys/dmu.h:600,
                 from /var/lib/dkms/zfs/0.6.2/build/module/zfs/../../module/zfs/dmu.c:27:
/var/lib/dkms/zfs/0.6.2/build/module/zfs/../../module/zfs/dmu.c: In function ‘dmu_req_copy’:
include/linux/bio.h:154:11: error: incompatible types when assigning to type ‘struct bio_vec’ from type ‘struct bio_vec *’
       bvl = bio_iovec_idx((bio), (i)), i < (bio)->bi_vcnt; \
           ^
include/linux/blkdev.h:751:3: note: in expansion of macro ‘bio_for_each_segment’
   bio_for_each_segment(bvl, _iter.bio, _iter.i)
   ^
/var/lib/dkms/zfs/0.6.2/build/include/linux/blkdev_compat.h:307:2: note: in expansion of macro ‘rq_for_each_segment’
  rq_for_each_segment(bv, rq, iter) \
  ^
/var/lib/dkms/zfs/0.6.2/build/module/zfs/../../module/zfs/dmu.c:1020:2: note: in expansion of macro ‘rq_for_each_segment4’
  rq_for_each_segment4(bv, bvp, req, iter) {
  ^
include/linux/bio.h:154:38: warning: left-hand operand of comma expression has no effect [-Wunused-value]
       bvl = bio_iovec_idx((bio), (i)), i < (bio)->bi_vcnt; \
                                      ^
include/linux/blkdev.h:751:3: note: in expansion of macro ‘bio_for_each_segment’
   bio_for_each_segment(bvl, _iter.bio, _iter.i)
   ^
/var/lib/dkms/zfs/0.6.2/build/include/linux/blkdev_compat.h:307:2: note: in expansion of macro ‘rq_for_each_segment’
  rq_for_each_segment(bv, rq, iter) \
  ^
/var/lib/dkms/zfs/0.6.2/build/module/zfs/../../module/zfs/dmu.c:1020:2: note: in expansion of macro ‘rq_for_each_segment4’
  rq_for_each_segment4(bv, bvp, req, iter) {
  ^
make[5]: *** [/var/lib/dkms/zfs/0.6.2/build/module/zfs/../../module/zfs/dmu.o] Error 1
```

I was able to successfully build a module off a commit 22760eebeff0e0ad826132b1be1113eecb39938a so I believe things broke by a commit b761912b3473f09a642eea21d609ce9bc1c91546
