### ISSUE TITLE
 zfs-2.1.4-78_g090bda59e (branch zfs-2.1.5-staging) kernel 5.18 dkms build error on RHEL 8.6 (Rocky Linux)

### ISSUE THREAD

**Issue by edefaria** [openzfs/zfs#13528]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| RHEL (Rocky Linux)
Distribution Version	| 8.6
Kernel Version	| 5.18.0-1.el8.elrepo.x86_64
Architecture	| x86_64
OpenZFS Version	| zfs-2.1.4-78_g090bda59e

### Describe the problem you're observing

Building zfs with elrepo kernel-ml 5.18 failed on dkms build, no issue building kernel-ml 5.17.

### Describe how to reproduce the problem

Install RHEL 8.6, download elrepo kernel-ml and clone/build zfs-2.1.5-staging with default behaviour:
$ ./autogen.sh
$ ./configure
$ make rpm
dkms failed to build on both kernel-ml 5.18.0-1.el8.elrepo.x86_64 and 5.18.1-1.el8.elrepo.x86_64.

### Include any warning/errors/backtraces from the system logs
https://gist.github.com/edefaria/f4d4f960ea277b1bdb57bfdf2dcd3a87

**Comment by tonyhutter** [comment]
For quick reference, here's one of the errors:  
```
    CC [M]  /var/lib/dkms/zfs/2.1.4/build/module/zfs/dsl_prop.o
In file included from ./include/linux/string.h:253,
                 from ./include/linux/bitmap.h:11,
                 from ./include/linux/cpumask.h:12,
                 from ./arch/x86/include/asm/cpumask.h:5,
                 from ./arch/x86/include/asm/msr.h:11,
                 from ./arch/x86/include/asm/processor.h:22,
                 from ./arch/x86/include/asm/timex.h:5,
                 from ./include/linux/timex.h:67,
                 from ./include/linux/time32.h:13,
                 from ./include/linux/time.h:60,
                 from ./include/linux/stat.h:19,
                 from ./include/linux/module.h:13,
                 from /var/lib/dkms/zfs/2.1.4/build/include/os/linux/spl/sys/atomic.h:27,
                 from /var/lib/dkms/zfs/2.1.4/build/include/sys/zfs_context.h:46,
                 from /var/lib/dkms/zfs/2.1.4/build/module/zfs/dsl_bookmark.c:22:
In function 'fortify_memset_chk',
    inlined from 'dsl_bookmark_set_phys' at /var/lib/dkms/zfs/2.1.4/build/module/zfs/dsl_bookmark.c:384:3:
./include/linux/fortify-string.h:242:4: error: call to '__write_overflow_field' declared with attribute warning: detected write beyond size of field (1st parameter); maybe use struct_group()? [-Werror]
    __write_overflow_field(p_size_field, size);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC [M]  /var/lib/dkms/zfs/2.1.4/build/module/zfs/dsl_scan.o
  CC [M]  /var/lib/dkms/zfs/2.1.4/build/module/zfs/dsl_synctask.o
  CC [M]  /var/lib/dkms/zfs/2.1.4/build/module/zfs/dsl_userhold.o
```   
I'm guessing you're hitting this since you're building with fortify source?  Here's the code in question:

```C
       } else {
              bzero(&zbm->zbm_flags,
                  sizeof (zfs_bookmark_phys_t) -
                  offsetof(zfs_bookmark_phys_t, zbm_flags));
       }
...


/*
 * On disk zap object.
 */
typedef struct zfs_bookmark_phys {
       uint64_t zbm_guid;          /* guid of bookmarked dataset */
       uint64_t zbm_creation_txg;  /* birth transaction group */
       uint64_t zbm_creation_time; /* bookmark creation time */

       /* fields used for redacted send / recv */
       uint64_t zbm_redaction_obj; /* redaction list object */
       uint64_t zbm_flags;         /* ZBM_FLAG_* */

       /* fields used for bookmark written size */
       uint64_t zbm_referenced_bytes_refd;
       uint64_t zbm_compressed_bytes_refd;
       uint64_t zbm_uncompressed_bytes_refd;
       uint64_t zbm_referenced_freed_before_next_snap;
       uint64_t zbm_compressed_freed_before_next_snap;
       uint64_t zbm_uncompressed_freed_before_next_snap;

       /* fields used for raw sends */
       uint64_t zbm_ivset_guid;
} zfs_bookmark_phys_t;
```
The bzero is correct - it's zeroing out zbm_flags and everything after it.  I get that the compiler would flag it though - it's worried were unintentionally trying to overwrite past the end of a field.

**Comment by behlendorf** [comment]
This appears to be the result of [this change](https://patchwork.kernel.org/project/linux-kbuild/patch/20210727205855.411487-35-keescook@chromium.org/) which was merged for the 5.18 kernel.  Seems like the approved way to address these false positives is to use the new `struct_group()` [macro](https://github.com/torvalds/linux/blob/master/include/linux/fortify-string.h#L291-L321).

**Comment by rhalualani** [comment]
I am currently running kernel 5.18.5-1.el8.elrepo.x86_64 for both Oracle8 and CentOS8
and also CentOS9 5.14.0-109.el9.x86_64
with zfs-2.1.99-1 which I got running "git clone https://github.com/zfsonlinux/zfs.git"
To get dkms to build for el8 (el9 was not an issue) I modified 4 files.
edonr.c dsl_bookmark.h dsl_bookmark.c and zfs_log.c
These were all warnings treated as errors.
In edonr.c at line 494 changed
    memcpy(hashState224(state)->DoublePipe, i512p2,
to  memcpy(hashState512(state)->DoublePipe, i512p2,

In dsl_bookmark.h added struct_group, ie. changed

typedef struct zfs_bookmark_phys {
    uint64_t zbm_guid;      /* guid of bookmarked dataset */
    uint64_t zbm_creation_txg;  /* birth transaction group */
    uint64_t zbm_creation_time; /* bookmark creation time */

    /* fields used for redacted send / recv */
    uint64_t zbm_redaction_obj; /* redaction list object */
    uint64_t zbm_flags;     /* ZBM_FLAG_* */

    /* fields used for bookmark written size */
    uint64_t zbm_referenced_bytes_refd;
    uint64_t zbm_compressed_bytes_refd;
    uint64_t zbm_uncompressed_bytes_refd;
    uint64_t zbm_referenced_freed_before_next_snap;
    uint64_t zbm_compressed_freed_before_next_snap;
    uint64_t zbm_uncompressed_freed_before_next_snap;

    /* fields used for raw sends */
    uint64_t zbm_ivset_guid;
} zfs_bookmark_phys_t;

TO:
typedef struct zfs_bookmark_phys {
    uint64_t zbm_guid;      /* guid of bookmarked dataset */
    uint64_t zbm_creation_txg;  /* birth transaction group */
    uint64_t zbm_creation_time; /* bookmark creation time */

    /* fields used for redacted send / recv */
    uint64_t zbm_redaction_obj; /* redaction list object */
    struct_group(zbm_group,
    uint64_t zbm_flags;     /* ZBM_FLAG_* */

    /* fields used for bookmark written size */
    uint64_t zbm_referenced_bytes_refd;
    uint64_t zbm_compressed_bytes_refd;
    uint64_t zbm_uncompressed_bytes_refd;
    uint64_t zbm_referenced_freed_before_next_snap;
    uint64_t zbm_compressed_freed_before_next_snap;
    uint64_t zbm_uncompressed_freed_before_next_snap;

    /* fields used for raw sends */
    uint64_t zbm_ivset_guid;
    ); /* end zbm_group group */
} zfs_bookmark_phys_t;

Then in dsl_bookmark.c Changed:
        memset(&zbm->zbm_flags, 0,
            sizeof (zfs_bookmark_phys_t) -
            offsetof(zfs_bookmark_phys_t, zbm_flags));
TO:
        memset(&zbm->zbm_group, 0,
            sizeof (zbm->zbm_group) );

Finally in zfs_log.c (A little dicey) Changed:
    memset(crtime, 0, 2 * sizeof (uint64_t));
    scanstamp = (caddr_t)(crtime + 2);
TO:
    memset(&crtime[0], 0, 2 * sizeof (uint64_t));
    scanstamp = (caddr_t)(&crtime[2]);

Seems to be working fine for both el8 and el9.

**Comment by akrherz** [comment]
Attempting dkms build of zfs 2.1.5 on 5.18.6-1.el8.elrepo.x86_64 and I get similar warnings / build failures
```
In file included from ./include/linux/string.h:253,
                 from ./include/linux/bitmap.h:11,
                 from ./include/linux/cpumask.h:12,
                 from ./arch/x86/include/asm/cpumask.h:5,
                 from ./arch/x86/include/asm/msr.h:11,
                 from ./arch/x86/include/asm/processor.h:22,
                 from ./arch/x86/include/asm/timex.h:5,
                 from ./include/linux/timex.h:67,
                 from ./include/linux/time32.h:13,
                 from ./include/linux/time.h:60,
                 from ./include/linux/stat.h:19,
                 from ./include/linux/module.h:13,
                 from /var/lib/dkms/zfs/2.1.5/build/include/os/linux/spl/sys/atomic.h:27,
                 from /var/lib/dkms/zfs/2.1.5/build/include/sys/zfs_context.h:46,
                 from /var/lib/dkms/zfs/2.1.5/build/module/zfs/dsl_bookmark.c:22:
In function ‘fortify_memset_chk’,
    inlined from ‘dsl_bookmark_set_phys’ at /var/lib/dkms/zfs/2.1.5/build/module/zfs/dsl_bookmark.c:384:3:
./include/linux/fortify-string.h:242:4: error: call to ‘__write_overflow_field’ declared with attribute warning: detected write beyond size of field (1st parameter); maybe use struct_group()? [-Werror]
    __write_overflow_field(p_size_field, size);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
In file included from ./include/linux/string.h:253,
                 from /var/lib/dkms/zfs/2.1.5/build/include/os/linux/spl/sys/strings.h:24,
                 from /var/lib/dkms/zfs/2.1.5/build/module/icp/algs/edonr/edonr.c:32:
In function ‘fortify_memcpy_chk’,
    inlined from ‘EdonRInit’ at /var/lib/dkms/zfs/2.1.5/build/module/icp/algs/edonr/edonr.c:491:3:
./include/linux/fortify-string.h:328:4: error: call to ‘__write_overflow_field’ declared with attribute warning: detected write beyond size of field (1st parameter); maybe use struct_group()? [-Werror]
    __write_overflow_field(p_size_field, size);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by behlendorf** [comment]
A proposed set of changes for this issue can be found in PR https://github.com/openzfs/zfs/pull/13575.
