### ISSUE TITLE
cannot compile on 2.6.38

### ISSUE THREAD

**Issue by Rudd-O** [openzfs/zfs#556]
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2   -o systemdescaper systemdescaper.o  -luuid -luuid -lz -lz -lz 
libtool: link: gcc -g -O2 -o systemdescaper systemdescaper.o  -luuid -lz
make[2]: Leaving directory `/usr/src/zfs/systemd'
Making all in module
make[2]: Entering directory`/usr/src/zfs/module'
make -C /usr/src/kernels/2.6.38.8-35.fc15.x86_64 SUBDIRS=`pwd`  modules
make[3]: Entering directory `/usr/src/kernels/2.6.38.8-35.fc15.x86_64'
  CC [M]  /usr/src/zfs/module/avl/../../module/avl/avl.o
  CC [M]  /usr/src/zfs/module/nvpair/../../module/nvpair/nvpair.o
  LD [M]  /usr/src/zfs/module/avl/zavl.o
  CC [M]  /usr/src/zfs/module/unicode/../../module/unicode/u8_textprep.o
  CC [M]  /usr/src/zfs/module/nvpair/../../module/nvpair/nvpair_alloc_spl.o
  CC [M]  /usr/src/zfs/module/unicode/../../module/unicode/uconv.o
  CC [M]  /usr/src/zfs/module/nvpair/../../module/nvpair/nvpair_alloc_fixed.o
  LD [M]  /usr/src/zfs/module/unicode/zunicode.o
  LD [M]  /usr/src/zfs/module/nvpair/znvpair.o
  CC [M]  /usr/src/zfs/module/zcommon/../../module/zcommon/zfs_deleg.o
  CC [M]  /usr/src/zfs/module/zfs/../../module/zfs/arc.o
  CC [M]  /usr/src/zfs/module/zcommon/../../module/zcommon/zfs_prop.o
/usr/src/zfs/module/zfs/../../module/zfs/arc.c: In function ‘arc_evict’:
/usr/src/zfs/module/zfs/../../module/zfs/arc.c:1754:3: error: implicit declaration of function ‘__SDEBUG’ [-Werror=implicit-function-declaration]
cc1: some warnings being treated as errors

9 <- ./deploy-zfs 
/usr/src@paola.dragonfear #:
uname -r
2.6.38.8-35.fc15.x86_64
