### ISSUE TITLE
Building 2.2.0 fails with missing symbols, 2.1.13 builds ok

### ISSUE THREAD

**Issue by rsms** [openzfs/zfs#15449]
### System information
Type | Version/Name
 --- | ---
Distribution Name | N/A (custom embedded linux)
Distribution Version  | N/A
Kernel Version  | Linux 6.5.8
Architecture  | x86_64
OpenZFS Version | 2.2.0 (release-tagged source)

### Describe the problem you're observing

Building 2.2.0 from source fails with `undefined reference to 'blkid_get_cache'`. However building 2.1.13 in the exact same environment (containerized) succeeds.

### Describe how to reproduce the problem

1. In a Linux chroot or container, build the following static libraries using GCC (I'm using 11.2.1) and musl libc:
  - install libc & linux headers
  - build libuuid & libblkid from util-linux 2.39.2
  - build openssl 3.1.3
  - build libtirpc 1.3.3
  - build attr 2.5.1
  - build bzip2 1.0.8
  - build zlib 1.3
  - build perl 5.38.0
  - build help2man 1.49.3
  - build m4 1.4.19
  - build libtool 2.4.7
  - build pkgconf 2.0.3

2. Fetch & extract zfs 2.2.0

```shell
$ curl -O https://github.com/openzfs/zfs/releases/download/zfs-2.2.0/zfs-2.2.0.tar.gz
$ tar -xf zfs-2.2.0.tar.gz
$ cd zfs-2.2.0
$ CFLAGS=-static CXXFLAGS=-static LDFLAGS=--static ./configure \
  --prefix=/usr \
  --with-udevdir=/tmp/non-existing \
  --with-tirpc \
  --with-config=user \
  --disable-systemd \
  --disable-shared
$ make
...
... undefined reference to `blkid_get_cache' ...
...
make: *** [Makefile:4591: all] Error 2
$ 
```

Note that if I attempt the exact same build with 2.1.13 it works:

```shell
$ curl -O https://github.com/openzfs/zfs/releases/download/zfs-2.1.13/zfs-2.1.13.tar.gz
$ tar -xf zfs-2.1.13.tar.gz
$ cd zfs-2.1.13
$ CFLAGS=-static CXXFLAGS=-static LDFLAGS=--static ./configure \
  --prefix=/usr \
  --with-udevdir=/tmp/non-existing \
  --with-tirpc \
  --with-config=user \
  --disable-systemd \
  --disable-shared
$ make
...
$ zpool --version
zfs-2.1.13-1
zfs-kmod-2.2.0-1
$
```

### Include any warning/errors/backtraces from the system logs

Example build session:

```
$ make
...
  CCLD     libzfs.la
ld: ./.libs/libzutil.a(libzutil_la-zutil_import_os.o): in function `zpool_find_import_blkid':
zutil_import_os.c:(.text+0x7e4): undefined reference to `blkid_get_cache'
ld: zutil_import_os.c:(.text+0x801): undefined reference to `blkid_probe_all_new'
ld: zutil_import_os.c:(.text+0x816): undefined reference to `blkid_put_cache'
ld: zutil_import_os.c:(.text+0x82a): undefined reference to `blkid_dev_iterate_begin'
ld: zutil_import_os.c:(.text+0x841): undefined reference to `blkid_put_cache'
ld: zutil_import_os.c:(.text+0x868): undefined reference to `blkid_dev_set_search'
ld: zutil_import_os.c:(.text+0x87d): undefined reference to `blkid_dev_iterate_end'
ld: zutil_import_os.c:(.text+0x889): undefined reference to `blkid_put_cache'
ld: zutil_import_os.c:(.text+0x8ef): undefined reference to `blkid_dev_devname'
ld: zutil_import_os.c:(.text+0xa08): undefined reference to `blkid_dev_next'
ld: zutil_import_os.c:(.text+0xa1c): undefined reference to `blkid_dev_iterate_end'
ld: zutil_import_os.c:(.text+0xa28): undefined reference to `blkid_put_cache'
ld: ./.libs/libzutil.a(libefi_la-rdwr_efi.o): in function `efi_alloc_and_init':
rdwr_efi.c:(.text+0x8ff): undefined reference to `uuid_generate'
ld: ./.libs/libzutil.a(libefi_la-rdwr_efi.o): in function `check_input':
rdwr_efi.c:(.text+0x2034): undefined reference to `uuid_is_null'
ld: ./.libs/libzutil.a(libefi_la-rdwr_efi.o): in function `efi_write':
rdwr_efi.c:(.text+0x3281): undefined reference to `uuid_is_null'
ld: rdwr_efi.c:(.text+0x32b6): undefined reference to `uuid_generate'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:5870: libzfs.la] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/build/zfs'
make: *** [Makefile:12070: install-recursive] Error 1
$
```
