### ISSUE TITLE
dkms error while installing 0.8.4 on CentOS 8 Stream

### ISSUE THREAD

**Issue by whatzgnu** [openzfs/zfs#10713]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| CentOS Stream
Distribution Version	| 8
Linux Kernel	| 4.18.0-211.el8.x86_64
Architecture	| x86_64
ZFS Version	| 0.8.4
SPL Version	| 0.8.4

### Describe the problem you're observing

DKMS compile error while upgrading from 0.8.2 to 0.8.4

### Describe how to reproduce the problem

wget http://download.zfsonlinux.org/epel/zfs-release.el8_2.noarch.rpm
sudo rpm -ivh zfs-release.el8_2.noarch.rpm
sudo dnf update

### Include any warning/errors/backtraces from the system logs

During install, the following error happened:

```
Loading new zfs-0.8.4 DKMS files...
Building for 4.18.0-211.el8.x86_64
Building initial module for 4.18.0-211.el8.x86_64
Error! Bad return status for module build on kernel: 4.18.0-211.el8.x86_64 (x86_64)
Consult /var/lib/dkms/zfs/0.8.4/build/make.log for more information.
warning: %post(zfs-dkms-0.8.4-1.el8.noarch) scriptlet failed, exit status 10
```

Looking at the make.log I see the following error:

```
...
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/zfs/uberblock.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/zfs/unique.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/zfs/vdev.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/zfs/vdev_cache.o
  CC [M]  /var/lib/dkms/zfs/0.8.4/build/module/zfs/vdev_disk.o
/var/lib/dkms/zfs/0.8.4/build/module/zfs/vdev_disk.c: In function ‘vdev_bio_associate_blkg’:
/var/lib/dkms/zfs/0.8.4/build/module/zfs/vdev_disk.c:520:22: error: implicit declaration of function ‘vdev_blkg_tryget’; did you mean ‘blkg_tryget’? [-Werror=implicit-function-declaration]
  if (q->root_blkg && vdev_blkg_tryget(q->root_blkg))
                      ^~~~~~~~~~~~~~~~
                      blkg_tryget
cc1: some warnings being treated as errors
make[5]: *** [scripts/Makefile.build:315: /var/lib/dkms/zfs/0.8.4/build/module/zfs/vdev_disk.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [scripts/Makefile.build:556: /var/lib/dkms/zfs/0.8.4/build/module/zfs] Error 2
make[3]: *** [Makefile:1545: _module_/var/lib/dkms/zfs/0.8.4/build/module] Error 2
make[3]: Leaving directory '/usr/src/kernels/4.18.0-211.el8.x86_64'
make[2]: *** [Makefile:30: modules] Error 2
make[2]: Leaving directory '/var/lib/dkms/zfs/0.8.4/build/module'
make[1]: *** [Makefile:841: all-recursive] Error 1
make[1]: Leaving directory '/var/lib/dkms/zfs/0.8.4/build'
make: *** [Makefile:710: all] Error 2
```

Attached are the config and make logs from DKMS. I ended up downgrading back to 0.8.2.
Let me know if you have any questions, thank you!

[config.log](https://github.com/openzfs/zfs/files/5074800/config.log)
[make.log](https://github.com/openzfs/zfs/files/5074801/make.log)

**Comment by prghix** [comment]
reporting the same. 0.8.5 on CentOS 8.3 standard, NON-stream.

**Comment by behlendorf** [comment]
https://github.com/openzfs/zfs/pull/11322
