### PR TITLE
Linux: Clang build fixes

### LINKED ISSUE #17951: compat 6.18 clang - build failing
### System information
Type | Version/Name
 --- | ---
Distribution Name	|  Garuda
Distribution Version	|  Soaring
Kernel Version	|  6.18-rc6
Architecture	|  x86_64
OpenZFS Version	| 2.4.99-225_g06c73cffab

### Describe the problem you're observing
on linux 6.18-rc6 the check config/kernel-kmap-atomic-args.m4 fails. The cause is that kmap_atomic had its argument changed to const in
[mm: constify highmem related functions for improved const-correctness](https://github.com/torvalds/linux/commit/a847b17009ec271514b269c90320a3893cd9b667)
happens only with clang, gcc passes.

modyfiing config/kernel-kmap-atomic-args.m4:
`struct page page; -> struct page page = {0};`
makes the check pass both on gcc and clang.

### Describe how to reproduce the problem
./configure KERNEL_LLVM=1 ...
### Include any warning/errors/backtraces from the system logs
- output from configure:

checking whether splice_copy_file_range() is available... yes
checking whether fops->remap_file_range() is available... yes
checking whether fops->clone_file_range() is available... no
checking whether fops->dedupe_file_range() is available... no
checking whether kmap_atomic wants 1 args... configure: error:
        *** None of the expected "kmap_atomic()" interfaces were detected.
        *** This may be because your kernel version is newer than what is
        *** supported, or you are using a patched custom kernel with
        *** incompatible modifications.
        ***
        *** ZFS Version: zfs-2.4.99-225_g06c73cffab
        *** Compatible Kernels: 4.18 - 6.17

- failing check, build/build.log.kabi:

kmap_atomic/kmap_atomic.c:78:16: error: variable 'page' is uninitialized when passed as a const pointer argument here [-Werror,-Wuninitialized-const-pointer]
78 |                 kmap_atomic(&page);
     |                                      ^~~~
kmap_local_page/kmap_local_page.c:78:20: error: variable 'page' is uninitialized when passed as a const pointer argument here [-Werror,-Wuninitialized-const-pointer]
78 |                 kmap_local_page(&page);
|                                  ^~~~
1 error generated.
1 error generated.
make[4]: *** [/tmp/makepkg/linux-cachyos-rc/src/linux-6.18-rc6/scripts/Makefile.build:287: kmap_atomic/kmap_atomic.o] Error 1
make[4]: *** [/tmp/makepkg/linux-cachyos-rc/src/linux-6.18-rc6/scripts/Makefile.build:287: kmap_local_page/kmap_local_page.o] Error 1
make[4]: Target 'kmap_atomic/' not remade because of errors.
make[4]: Target 'kmap_local_page/' not remade because of errors.
make[3]: *** [/tmp/makepkg/linux-cachyos-rc/src/linux-6.18-rc6/scripts/Makefile.build:556: kmap_atomic] Error 2
CC [M]  i_uid_read/i_uid_read.o
make[3]: *** [/tmp/makepkg/linux-cachyos-rc/src/linux-6.18-rc6/scripts/Makefile.build:556: kmap_local_page] Error 2

### LINKED ISSUE #17959: zfs 2.3.5: compilation error with clang
This is a report for an up-to-date  endeavouros with 

```
clang 21.1.5-1
llvm 21.1.5-1
llvm-libs 21.1.5-1
```

I am using the linux-tkg kernels. I typically use gcc but today I wanted to try the llvm toolchain.

The gcc build works fine.

When I compile kernel 6.12.58 with llvm I get a zfs-dkms build fail:

From `/var/lib/dkms/zfs/2.3.5/build/make.log` :
```
...
checking whether bio->bi_bdev->bd_disk exists... yes
checking whether block_device_operations->submit_bio() returns void... yes
checking whether bio_alloc() wants 4 args... yes
checking whether blkdev_get_by_path() exists and takes 3 args... no
checking whether blkdev_get_by_path() exists and takes 4 args... no
checking whether bdev_open_by_path() exists... no
checking whether bdev_file_open_by_path() exists... no
configure: error: 
	*** None of the expected "blkdev_get_by_path()" interfaces were detected.
	*** This may be because your kernel version is newer than what is
	*** supported, or you are using a patched custom kernel with
	*** incompatible modifications.
	***
	*** ZFS Version: zfs-2.3.5-1
	*** Compatible Kernels: 4.18 - 6.17
	

# exit code: 1
# elapsed time: 00:00:32
```

I am not aware of any incompatible linux-tkg changes. Thats why I am posting this here.

### PR DESCRIPTION
**Pull request by robn**
### Motivation and Context

Recent Clang is a little upset with a handful of things on the Linux side. This sorts it out.

Fixes #17951
Fixes #17959

### Description

See commit messages. Summary:

- Linux: don't explicitly declare -std=gnu99
- zvol_id: make array length properly known at compile time
- config/kmap_atomic: initialise test data

### How Has This Been Tested?

Compiled and basic sanity runs done with GCC 14.2 and Clang 17, 19 and 22 against Linux 6.1.x, 6.16.x and 6.18-rc.

Not my usual comprehensive set, but recompiling kernels as well adds a lot of time and building with Clang is more difficult the older they get.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Quality assurance (non-breaking change which makes the code more robust against bugs)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: module/Kbuild.in [hunk 1]
```diff
@@ -2,7 +2,7 @@
 # first.  This ensures its module initialization function is run before
 # any of the other module initialization functions which depend on it.
 
-ZFS_MODULE_CFLAGS += -std=gnu99 -Wno-declaration-after-statement
+ZFS_MODULE_CFLAGS += -Wno-declaration-after-statement
```
Comment (behlendorf) [inline module/Kbuild.in]: Interestingly, this breaks the build on almalinux8.  I haven't looked closely but it sure looks like it's defaulting to C89/C90 here.

```
   /tmp/zfs-build-zfs-DRBBnzeA/BUILD/zfs-2.4.99/module/os/linux/spl/spl-kmem-cache.c: In function 'spl_slab_alloc':
  /tmp/zfs-build-zfs-DRBBnzeA/BUILD/zfs-2.4.99/module/os/linux/spl/spl-kmem-cache.c:272:2: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
    for (int i = 0; i < sks->sks_objs; i++) {
    ^~~
  /tmp/zfs-build-zfs-DRBBnzeA/BUILD/zfs-2.4.99/module/os/linux/spl/spl-kmem-cache.c:272:2: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
  /tmp/zfs-build-zfs-DRBBnzeA/BUILD/zfs-2.4.99/module/os/linux/spl/spl-kmem-cache.c: In function 'spl_cache_flush':
  /tmp/zfs-build-zfs-DRBBnzeA/BUILD/zfs-2.4.99/module/os/linux/spl/spl-kmem-cache.c:500:2: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
    for (int i = 0; i < count; i++)
    ^~~
```

Comment (robn) [reply module/Kbuild.in]: Ahh, interesting, I'd missed a detail. Kernel changed to gnu11 in 5.18.x, before that it was gnu89, far too old.

Last push changes that commit to force gnu11 for us instead. Seems to build ok on 4.19 with GCC. Well see what the builders make of it.

**Comment by JohnyPeaN** [comment]
Tested it without the -std=gnu99 and now with -std=gnu11 change and both work. Solves the #17951, thanks.

**Comment by alex-moch** [comment]
This does _not_ fix #17959 for me. #17684 fixes the build with LLVM/Clang 21 on 2.2.9 and 2.3.5.
