### ISSUE TITLE
dkms fails to compile zfs on armbian 6.19.6

### ISSUE THREAD

**Issue by citroboy** [openzfs/zfs#18291]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Armbian (Debian Trixie)
Distribution Version	| 26.2.0-trunk.542 edge
Kernel Version	| 6.19.6
Architecture	| aarch64
OpenZFS Version	| 2.4.0-1

### Describe the problem you're observing
Updating to the latest kernel the zfs module build fails.

### Describe how to reproduce the problem
Running kernel 6.17.1-edge-rockchip64
sudo apt full-upgrade (twice, the first time fails saying CONFIG_MODULES=n)
installs 6.19.6-edge-rockchip64 but
```
Setting up linux-image-edge-rockchip64 (26.2.0-trunk.542) ...
Armbian 'linux-image-edge-rockchip64' for '6.19.6-edge-rockchip64': 'postinst' starting.
The kernel is built without module signing facility, modules won't be signed

Autoinstall of module zfs/2.4.0 for kernel 6.19.6-edge-rockchip64 (aarch64)
Running the pre_build script................................ done.
Building module(s)...............................(bad exit status: 2)
Failed command:
make -j8 KERNELRELEASE=6.19.6-edge-rockchip64

Error! Bad return status for module build on kernel: 6.19.6-edge-rockchip64 (aarch64)
Consult /var/lib/dkms/zfs/2.4.0/build/make.log for more information.

Autoinstall on 6.19.6-edge-rockchip64 failed for module(s) zfs(10).

Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
run-parts: /etc/kernel/postinst.d/dkms exited with return code 1
```

### Include any warning/errors/backtraces from the system logs

The make log says:
```
configure: WARNING:

        You are building OpenZFS against Linux version 6.19.6-edge-rockchip64.

        This combination is considered EXPERIMENTAL by the OpenZFS project.
...
make -C /lib/modules/6.19.6-edge-rockchip64/build CC=aarch64-linux-gnu-gcc \
          \
         \
         \
         \
        M="$PWD"  CONFIG_ZFS=m modules
make[3]: Entering directory '/usr/src/linux-headers-6.19.6-edge-rockchip64'
make[4]: Entering directory '/var/lib/dkms/zfs/2.4.0/build/module'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: aarch64-linux-gnu-gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  You are using:           aarch64-linux-gnu-gcc (Debian 14.2.0-19) 14.2.0
  CC [M]  os/linux/spl/spl-atomic.o
...
  CC [M]  os/linux/zfs/zpl_file.o
/var/lib/dkms/zfs/2.4.0/build/module/os/linux/zfs/zfs_vnops_os.c: In function ‘zfs_link’:
/var/lib/dkms/zfs/2.4.0/build/module/os/linux/zfs/zfs_vnops_os.c:3516:58: error: invalid operands to binary & (have ‘struct inode_state_flags’ and ‘int’)
 3516 |         is_tmpfile = (sip->i_nlink == 0 && (sip->i_state & I_LINKABLE));
      |                                             ~~~~~~~~~~~~ ^
      |                                                |
      |                                                struct inode_state_flags
make[6]: *** [Kbuild:528: os/linux/zfs/zfs_vnops_os.o] Error 1
```

**Comment by behlendorf** [comment]
As the error message say, the zfs-2.4.0 release does not support the 6.19 kernel.  I'd suggest opening an issue with the Armbian maintainers to update to zfs-2.4.1 which adds support for 6.19 kernels.
