### ISSUE TITLE
2.1.4 is unable to build on ubuntu LTS 22.04 

### ISSUE THREAD

**Issue by liyimeng** [openzfs/zfs#13524]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| ubuntu 
Distribution Version	|  22.04
Kernel Version	| 5.15.0-33
Architecture	|. x86_64
OpenZFS Version	| 2.1.4

### Describe the problem you're observing
I try to build 2.1.4 from source on ubuntu 22.04, it failed to build and throw error on 'strlcpy'
Now sure what I am missing. 
### Describe how to reproduce the problem

Install ubuntu 22.04, download 2.1.4 source and try to build. 

### Include any warning/errors/backtraces from the system logs

```
configure:67388: result: no
configure:67394: checking for strlcpy
configure:67394: gcc -o conftest -g -O2   conftest.c  >&5
/usr/bin/ld: /tmp/ccliDnPJ.o: in function `main':
/usr/src/zfs/conftest.c:103: undefined reference to `strlcpy'
collect2: error: ld returned 1 exit status
configure:67394: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "zfs"
| #define PACKAGE_TARNAME "zfs"
| #define PACKAGE_VERSION "2.1.4"
| #define PACKAGE_STRING "zfs 2.1.4"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define ZFS_META_NAME "zfs"
| #define ZFS_META_VERSION "2.1.4"
| #define SPL_META_VERSION ZFS_META_VERSION
| #define ZFS_META_RELEASE "1"
| #define SPL_META_RELEASE ZFS_META_RELEASE
| #define ZFS_META_LICENSE "CDDL"
| #define ZFS_META_ALIAS "zfs-2.1.4-1"
| #define SPL_META_ALIAS ZFS_META_ALIAS
| #define ZFS_META_AUTHOR "OpenZFS"
| #define ZFS_META_KVER_MIN "3.10"
| #define ZFS_META_KVER_MAX "5.17"
| #define PACKAGE "zfs"
| #define VERSION "2.1.4"
| #define HAVE_STDIO_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_UNISTD_H 1
| #define STDC_HEADERS 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| #define HAVE_IMPLICIT_FALLTHROUGH 1
| #define HAVE_SSE 1
| #define HAVE_SSE2 1
| #define HAVE_SSE3 1
| #define HAVE_SSSE3 1
| #define HAVE_SSE4_1 1
| #define HAVE_SSE4_2 1
| #define HAVE_AVX 1
| #define HAVE_AVX2 1
| #define HAVE_AVX512F 1
| #define HAVE_AVX512CD 1
| #define HAVE_AVX512DQ 1
| #define HAVE_AVX512BW 1
| #define HAVE_AVX512IFMA 1
| #define HAVE_AVX512VBMI 1
| #define HAVE_AVX512PF 1
| #define HAVE_AVX512ER 1
| #define HAVE_AVX512VL 1
| #define HAVE_AES 1
| #define HAVE_PCLMULQDQ 1
| #define HAVE_MOVBE 1
| #define HAVE_XSAVE 1
| #define HAVE_XSAVEOPT 1
| #define HAVE_XSAVES 1
| #define SYSTEM_LINUX 1
| #define ENABLE_NLS 1
| #define HAVE_GETTEXT 1
| #define HAVE_DCGETTEXT 1
| #define HAVE_ZLIB 1
| #define HAVE_LIBUUID 1
| #define HAVE_LIBBLKID 1
| #define HAVE_LIBTIRPC 1
| #define HAVE_LIBUDEV 1
| #define HAVE_UDEV_DEVICE_GET_IS_INITIALIZED 1
| #define HAVE_LIBCRYPTO 1
| #define HAVE_LIBAIO 1
| #define LIBFETCH_IS_FETCH 0
| #define LIBFETCH_IS_LIBCURL 0
| #define LIBFETCH_DYNAMIC 0
| #define LIBFETCH_SONAME ""
| #define HAVE_MAKEDEV_IN_SYSMACROS 1
| #define HAVE_MLOCKALL 1
| /* end confdefs.h.  */
| /* Define strlcpy to an innocuous variant, in case <limits.h> declares strlcpy.
|    For example, HP-UX 11i <limits.h> declares gettimeofday.  */
| #define strlcpy innocuous_strlcpy
| 
| /* System header to define __stub macros and hopefully few prototypes,
|    which can conflict with char strlcpy (); below.  */
| 
| #include <limits.h>
| #undef strlcpy
| 
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char strlcpy ();
| /* The GNU C library defines this for functions which it implements
|     to always fail with ENOSYS.  Some functions are actually named
|     something starting with __ and the normal name is an alias.  */
| #if defined __stub_strlcpy || defined __stub___strlcpy
| choke me
| #endif
| 
| int
| main (void)
| {
| return strlcpy ();
|   ;
|   return 0;
| }
configure:67394: result: no
configure:67422: checking kernel source and build directories
configure:67505: result: done
configure:67507: checking kernel source directory
configure:67509: result: /usr/src/linux-headers-5.15.0-33-generic
configure:67511: checking kernel build directory
configure:67513: result: /usr/src/linux-headers-5.15.0-33-generic
configure:67526: checking kernel source version
configure:67579: result: 5.15.0-33-generic
configure:67611: checking kernel file name for module symbols
configure:67644: result: Module.symvers
configure:67755: checking whether modules can be built
configure:67931: 
            KBUILD_MODPOST_NOFINAL= KBUILD_MODPOST_WARN=
            make modules -k -j8    -C /usr/src/linux-headers-5.15.0-33-generic 
            M=/usr/src/zfs/build/conftest >build/conftest/build.log 2>&1
configure:67934: $? = 2
configure:67937: test -f build/conftest/conftest.ko
configure:67940: $? = 1
configure:67949: result: no
configure:67952: error: 
        *** Unable to build an empty module.

```

**Comment by liyimeng** [comment]
Could be my env problem. I create a new VM and build, it pass the check.

**Comment by liyimeng** [comment]
It is still the case

**Comment by liyimeng** [comment]
If this `workaround` has no negative impact, I will close this issue.

**Comment by rincebrain** [comment]
That...shouldn't be necessary, and wasn't for me. amd64 was never a folder in there - back before it was merged (in the 2.6 days!), it was x86_64.

**Comment by liyimeng** [comment]
that is strange, so x86 should take care of both x86/x86_64.  I was building it in docker, might be docker set arch to amd64 instead of x86_64?

**Comment by liyimeng** [comment]
I'll close this since it is not zfs defect.
