### ISSUE TITLE
0.6.0-rc13 FC18 32-bit build issue

### ISSUE THREAD

**Issue by behlendorf** [openzfs/zfs#1254]
```
1:zfs-modules-dkms-0.6.0-rc13 ################################# [100%]
Loading new zfs-0.6.0 DKMS files...
First Installation: checking all kernels...
Building only for 3.6.10-4.fc18.i686.PAE
Building initial module for 3.6.10-4.fc18.i686.PAE
Error! Bad return status for module build on kernel: 3.6.10-4.fc18.i686.PAE (i686)
Consult /var/lib/dkms/zfs/0.6.0/build/make.log for more information.
warning: %post(zfs-modules-dkms-0.6.0-rc13.noarch) scriptlet failed, exit status 10

make.log

...

CC [M] /var/lib/dkms/zfs/0.6.0/build/module/zfs/../../module/zfs/arc.o
/var/lib/dkms/zfs/0.6.0/build/module/zfs/../../module/zfs/arc.c: In function ‘buf_hash_insert’:
/var/lib/dkms/zfs/0.6.0/build/module/zfs/../../module/zfs/arc.c:789:3: warning: ‘__ret’ may be used uninitialized in this function [-Wuninitialized]
/var/lib/dkms/zfs/0.6.0/build/module/zfs/../../module/zfs/arc.c:793:2: warning: ‘__ret’ may be used uninitialized in this function [-Wuninitialized]
/var/lib/dkms/zfs/0.6.0/build/module/zfs/../../module/zfs/arc.c:789:3: error: call to ‘__cmpxchg_wrong_size’ declared with attribute error: Bad argument size for cmpxchg
/var/lib/dkms/zfs/0.6.0/build/module/zfs/../../module/zfs/arc.c:793:2: error: call to ‘__cmpxchg_wrong_size’ declared with attribute error: Bad argument size for cmpxchg
make[5]: *** [/var/lib/dkms/zfs/0.6.0/build/module/zfs/../../module/zfs/arc.o] Error 1
make[4]: *** [/var/lib/dkms/zfs/0.6.0/build/module/zfs] Error 2
make[3]: *** [_module_/var/lib/dkms/zfs/0.6.0/build/module] Error 2
make[3]: Leaving directory `/usr/src/kernels/3.6.10-4.fc18.i686.PAE'
make[2]: *** [modules] Error 2
make[2]: Leaving directory `/var/lib/dkms/zfs/0.6.0/build/module' 
```
