### ISSUE TITLE
FreeBSD 13 buildbot is broken

### ISSUE THREAD

**Issue by ryao** [openzfs/zfs#14616]
Builds are being done against 13.2-beta3, but FreeBSD has removed the tarballs and now have ones for -rc2 on their website. Perhaps we should have builds done against 13.1 instead for the time being.

**Comment by ryao** [comment]
> I think just repointing it at the stable/13 snapshots is probably The Right Thing to do, since it was failing because it tried to grab src.txz from a URL that stopped existing after a week or so.

After thinking about it, I would like to see more branches tested. When the current stable branch is broken, having builds tested against the older stable branch would still be useful because it would warn us about issues like 9fa007d35dd3ab231034e766f643510c5976ffc9 so that we do not merge PRs that break FreeBSD builds.

**Comment by brd** [comment]
13.2-RELEASE has now shipped so it can be used.

I am interested in this, how can I help?

**Comment by ryao** [comment]
openzfs/zfs-buildbot#272 should fix this.

**Comment by behlendorf** [comment]
This change has been merged and FreeBSD 13.2 builds are working again.

**Comment by lundman** [comment]
Are these related?

```
In file included from /var/lib/buildbot/slaves/zfs/FreeBSD_stable_13_amd64__TEST_/build/zfs/module/os/freebsd/zfs/dmu_os.c:39:
/var/lib/buildbot/slaves/zfs/FreeBSD_stable_13_amd64__TEST_/build/zfs/include/sys/dmu_objset.h:76:15: error: field 'os_meta_dnode' with variable sized type 'dnode_phys_t' (aka 'struct dnode_phys') not at the end of a struct or class is a GNU extension [-Werror,-Wgnu-variable-sized-type-not-at-end]
        dnode_phys_t os_meta_dnode;

```

**Comment by behlendorf** [comment]
These are a new errors inadvertently introduced by 27a82cbb3ef2e30a54860b955fb257fb7f8307cd.  We should either revert that change or find some reasonable way to handle the warnings on FreeBSD.

**Comment by lundman** [comment]
Ah ok, fixed the build bot so it runs, next freebsd can fix the build :)

**Comment by behlendorf** [comment]
I'd added a comment to https://github.com/openzfs/zfs/pull/14737#issuecomment-1512294105 about this.  If you have a preferred way to address this please chime in.  We're going to want to do something to resolve this fairly promptly.

**Comment by lundman** [comment]
I'll have look, I was more worried I had broken it

**Comment by youzhongyang** [comment]
PR #14763 was created. If you have any better way addressing this issue, please share.
