### ISSUE TITLE
Can't compile with 3.1 kernel (Ubuntu x86_64)

### ISSUE THREAD

**Issue by colorprint** [openzfs/zfs#387]
Can't compile the SPL and ZFS kernel modules with 3.1-rc4 kernel (Ubuntu):

  CC [M]  /var/lib/dkms/spl/0.6.0.31/build/module/spl/../../module/spl/spl-debug.o
/var/lib/dkms/spl/0.6.0.31/build/module/spl/../../module/spl/spl-debug.c: In function ‘spl_debug_dump_all_pages’:
/var/lib/dkms/spl/0.6.0.31/build/module/spl/../../module/spl/spl-debug.c:963:9: error: too few arguments to function ‘filp->f_op->fsync’
