### ISSUE TITLE
Does not compile on kernel 2.6.38

### ISSUE THREAD

**Issue by Rudd-O** [openzfs/zfs#162]
Oops...  zfs does not compile in kernel 2.6.38 which I am trying to run right now, see if it solves the thrashing problem.

```
Making all in module
make[2]: Entering directory `/home/rudd-o/Projects/Mine/zfs/module'
make -C /home/rudd-o/Projects/Third-party/linux/build/karen.dragonfear SUBDIRS=`pwd`      O=/home/rudd-o/Projects/Third-party/linux/build/karen.dragonfear modules
make[3]: Entering directory `/home/rudd-o/Projects/Third-party/linux/build/karen.dragonfear'
make -C /home/rudd-o/Projects/Third-party/linux/source O=/home/rudd-o/Projects/Third-party/linux/build/karen.dragonfear/. modules
  CC [M]  /home/rudd-o/Projects/Mine/zfs/module/zcommon/../../module/zcommon/zfs_prop.o
In file included from /home/rudd-o/Projects/Mine/zfs/include/sys/zfs_acl.h:31:0,
             from /home/rudd-o/Projects/Mine/zfs/module/zcommon/../../module/zcommon/zfs_prop.c:30:
/home/rudd-o/Projects/Mine/zfs/include/sys/xvattr.h:49:16: error: redefinition of ‘struct xoptattr’
/usr/src/spl-0.6.0/2.6.38karen.dragonfear/sys/vnode.h:146:16: note: originally defined here
/home/rudd-o/Projects/Mine/zfs/include/sys/xvattr.h:67:3: error: conflicting types for ‘xoptattr_t’
/usr/src/spl-0.6.0/2.6.38karen.dragonfear/sys/vnode.h:160:3: note: previous declaration of ‘xoptattr_t’ was here
/home/rudd-o/Projects/Mine/zfs/include/sys/xvattr.h:133:16: error: redefinition of ‘struct xvattr’
/usr/src/spl-0.6.0/2.6.38karen.dragonfear/sys/vnode.h:162:16: note: originally defined here
/home/rudd-o/Projects/Mine/zfs/include/sys/xvattr.h:141:3: error: conflicting types for ‘xvattr_t’
/usr/src/spl-0.6.0/2.6.38karen.dragonfear/sys/vnode.h:170:3: note: previous declaration of ‘xvattr_t’ was here
/home/rudd-o/Projects/Mine/zfs/include/sys/xvattr.h: In function ‘xva_init’:
/home/rudd-o/Projects/Mine/zfs/include/sys/xvattr.h:280:28: error: ‘ATTR_XVATTR’ undeclared (first use in this function)
/home/rudd-o/Projects/Mine/zfs/include/sys/xvattr.h:280:28: note: each undeclared identifier is reported only once for each function it appears in
/home/rudd-o/Projects/Mine/zfs/include/sys/xvattr.h: At top level:
/home/rudd-o/Projects/Mine/zfs/include/sys/xvattr.h:303:0: warning: "V_ACE_MASK" redefined
/usr/src/spl-0.6.0/2.6.38karen.dragonfear/sys/vnode.h:97:0: note: this is the location of the previous definition
/home/rudd-o/Projects/Mine/zfs/include/sys/xvattr.h:304:0: warning: "V_APPEND" redefined
/usr/src/spl-0.6.0/2.6.38karen.dragonfear/sys/vnode.h:98:0: note: this is the location of the previous definition
/home/rudd-o/Projects/Mine/zfs/include/sys/xvattr.h:310:16: error: redefinition of ‘struct vsecattr’
/usr/src/spl-0.6.0/2.6.38karen.dragonfear/sys/vnode.h:172:16: note: originally defined here
/home/rudd-o/Projects/Mine/zfs/include/sys/xvattr.h:318:3: error: conflicting types for ‘vsecattr_t’
/usr/src/spl-0.6.0/2.6.38karen.dragonfear/sys/vnode.h:180:3: note: previous declaration of ‘vsecattr_t’ was here
make[7]: *** [/home/rudd-o/Projects/Mine/zfs/module/zcommon/../../module/zcommon/zfs_prop.o] Error 1
make[6]: *** [/home/rudd-o/Projects/Mine/zfs/module/zcommon] Error 2
make[5]: *** [_module_/home/rudd-o/Projects/Mine/zfs/module] Error 2
make[4]: *** [sub-make] Error 2
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/rudd-o/Projects/Third-party/linux/build/karen.dragonfear'
make[2]: *** [modules] Error 2
make[2]: Leaving directory `/home/rudd-o/Projects/Mine/zfs/module'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/rudd-o/Projects/Mine/zfs'
make: *** [all] Error 2
```
