### ISSUE TITLE
ZPL 0.6.0 RC1 fails to build on Ubuntu 9.10 2.6.31-22-generic 

### ISSUE THREAD

**Issue by rryan** [openzfs/zfs#135]
Building the ZPL under Ubuntu 9.10, 

uname -a shows:
Linux xyz 2.6.31-22-generic #73-Ubuntu SMP Fri Feb 11 19:18:05 UTC 2011 x86_64 GNU/Linux

The symbol seq_printf seems to be missing:

  CC [M]  /tmp/zfs-build-rjryan-U8G35Lgf/BUILD/zfs-0.6.0/module/zfs/../../module/zfs/zpl_super.o
/tmp/zfs-build-rjryan-U8G35Lgf/BUILD/zfs-0.6.0/module/zfs/../../module/zfs/zpl_super.c: In function ‘zpl_show_options’:
/tmp/zfs-build-rjryan-U8G35Lgf/BUILD/zfs-0.6.0/module/zfs/../../module/zfs/zpl_super.c:130: error: implicit declaration of function ‘seq_printf’
make[7]: **\* [/tmp/zfs-build-rjryan-U8G35Lgf/BUILD/zfs-0.6.0/module/zfs/../../module/zfs/zpl_super.o] Error 1
