### ISSUE TITLE
zfs-2.1.3/module/zfs/arc.c:1208:17: error: unused variable ‘hdr’

### ISSUE THREAD

**Issue by dniasoff** [openzfs/zfs#13194]
Compiling on Centos 8 Stream with latest elrep kernel-ml  5.16.13-1.el8.elrepo.x86_64 fails

```
Making all in module
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4)
  You are using:           gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10)
/root/zfs-2.1.3/module/zfs/arc.c: In function ‘hdr_l2only_dest’:
/root/zfs-2.1.3/module/zfs/arc.c:1208:17: error: unused variable ‘hdr’ [-Werror=unused-variable]
  arc_buf_hdr_t *hdr = vbuf;
                 ^~~
cc1: all warnings being treated as errors
make[5]: *** [scripts/Makefile.build:287: /root/zfs-2.1.3/module/zfs/arc.o] Error 1
make[4]: *** [scripts/Makefile.build:549: /root/zfs-2.1.3/module/zfs] Error 2
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [Makefile:1846: /root/zfs-2.1.3/module] Error 2
make[2]: *** [Makefile:55: modules-Linux] Error 2
make[1]: *** [Makefile:920: all-recursive] Error 1
```

### System information
Distribution Name	| Centos-Stream
Distribution Version	| 8
Kernel Version	| 5.16.13-1.el8.elrepo.x86_64
Architecture	| x886_64
OpenZFS Version	| 2.1.3

**Comment by Space2Man** [comment]
Hi!

I am running into the same issue on gentoo x86_64, x86_64-pc-linux-gnu-11.2.1.

**Comment by TheUbuntuGuy** [comment]
A quick fix to get things building:

```diff
--- a/module/zfs/arc.c
+++ b/module/zfs/arc.c
@@ -1206,7 +1206,7 @@ hdr_l2only_dest(void *vbuf, void *unused)
 {
 	(void) unused;
 	arc_buf_hdr_t *hdr = vbuf;
-
+	(void) hdr;
 	ASSERT(HDR_EMPTY(hdr));
 	arc_space_return(HDR_L2ONLY_SIZE, ARC_SPACE_L2HDRS);
 }
```

**Comment by dniasoff** [comment]
works for me. Thanks @TheUbuntuGuy

**Comment by nabijaczleweli** [comment]
Heh. I'd say that GCC is wrong to say this, since `hdr` *is* used, just in an unevaluated context. Fixed in #13195

**Comment by dniasoff** [comment]
tried your patch @nabijaczleweli  but 
```
../../module/zfs/arc.c: In function 'buf_dest':
../../module/zfs/arc.c:1220:17: error: 'buf' undeclared (first use in this function); did you mean 'vbuf'?
  mutex_destroy(&buf->b_evict_lock);
                 ^~~
                 vbuf
../../module/zfs/arc.c:1220:17: note: each undeclared identifier is reported only once for each function it appears in
  CC       bqueue.lo
  CC       cityhash.lo
make[5]: *** [Makefile:1336: arc.lo] Error 1
make[5]: *** Waiting for unfinished jobs....
```

**Comment by TheUbuntuGuy** [comment]
The patch is for the v2.1.3 release, not master. The file offset is wrong and it's patching the wrong function.

**Comment by freqlabs** [comment]
I've run into this on FreeBSD as well. I'm working on a PR against zfs-2.1-release.

**Comment by freqlabs** [comment]
Please try this patch:
```diff
diff --git a/module/zfs/arc.c b/module/zfs/arc.c
index 9984c2d27..47b58b6c2 100644
--- a/module/zfs/arc.c
+++ b/module/zfs/arc.c
@@ -1205,7 +1205,7 @@ static void
 hdr_l2only_dest(void *vbuf, void *unused)
 {
        (void) unused;
-       arc_buf_hdr_t *hdr = vbuf;
+       arc_buf_hdr_t *hdr __maybe_unused = vbuf;
 
        ASSERT(HDR_EMPTY(hdr));
        arc_space_return(HDR_L2ONLY_SIZE, ARC_SPACE_L2HDRS);
```

**Comment by freqlabs** [comment]
Ah right there was already a working patch posted here. I'm sure this will work then.

**Comment by nabijaczleweli** [comment]
Oh, yeah #13195 is a different thing, I hadn't realised 2.1.x still has non-void-casted ASSERTs. In that case `__maybe_unused` is the only option.

**Comment by bugalo** [comment]
> A quick fix to get things building:
> 
> ```diff
> --- a/module/zfs/arc.c
> +++ b/module/zfs/arc.c
> @@ -1206,7 +1206,7 @@ hdr_l2only_dest(void *vbuf, void *unused)
>  {
>  	(void) unused;
>  	arc_buf_hdr_t *hdr = vbuf;
> -
> +	(void) hdr;
>  	ASSERT(HDR_EMPTY(hdr));
>  	arc_space_return(HDR_L2ONLY_SIZE, ARC_SPACE_L2HDRS);
>  }
> ```

Thanks! Your patch works in Gentoo, for zfs-2.1.3.
