### ISSUE TITLE
Building master is broken by 2a068a1394d179dda4becf350e3afb4e8819675e

### ISSUE THREAD

**Issue by ryao** [openzfs/zfs#14057]
### System information

Type | Version/Name
 --- | ---
Distribution Name	|Gentoo
Distribution Version	|2.9
Kernel Version	|5.16.14-gentoo-x86_64
Architecture	|x86_64
OpenZFS Version	|master

### Describe the problem you're observing
Building master fails with:
```
tests/zfs-tests/cmd/idmap_util.c:103:8: error: redefinition of ‘struct mount_attr’
  103 | struct mount_attr {
      |        ^~~~~~~~~~
In file included from /usr/include/sys/mount.h:32,
                 from ./lib/libspl/include/os/linux/sys/mount.h:27,
                 from ./lib/libspl/include/os/linux/sys/stat.h:31,
                 from tests/zfs-tests/cmd/idmap_util.c:33:
/usr/include/linux/mount.h:129:8: note: originally defined here
  129 | struct mount_attr {
      |        ^~~~~~~~~~
```
### Describe how to reproduce the problem
```
git clone https://github.com/openzfs/zfs.git
cd zfs
git clean -xdf && ./autogen.sh && ./configure --enable-debug --enable-debuginfo --with-config=all && make -j$(nproc)
```

2a068a1394d179dda4becf350e3afb4e8819675e introduced this code.

The problem code is:
```
#ifndef mount_attr
struct mount_attr {
        __u64 attr_set;
        __u64 attr_clr;
        __u64 propagation;
        __u64 userns_fd;
};
#endif
```
I am not sure how this was expected to work in the first place. You cannot use the CPP to check what C structures are defined. An autotools check is needed for that.

**Comment by youzhongyang** [comment]
I am also confused, how could it pass all the builds, including my manual ones on newer and older kernels. Anyway your fix looks good.

**Comment by youzhongyang** [comment]
I am not convinced. Here are output from 3 different systems:
```
# grep 'struct mount_attr' /usr/include/linux/mount.h ; uname -r
#define MOUNT_ATTR_IDMAP        0x00100000 /* Idmap mount to @userns_fd in struct mount_attr. */
struct mount_attr {
5.15.0-46-lowlatency

# grep 'struct mount_attr' /usr/include/linux/mount.h ; uname -r
#define MOUNT_ATTR_IDMAP        0x00100000 /* Idmap mount to @userns_fd in struct mount_attr. */
struct mount_attr {
5.19.0-17-generic

# grep 'struct mount_attr' /usr/include/linux/mount.h ; uname -r
4.18.0-408.el8.x86_64
```
I have no problem building on them.

**Comment by ryao** [comment]
Do any of them use glibc 2.36?

**Comment by 65a** [comment]
broken here as well, also on an affected glibc

**Comment by youzhongyang** [comment]
ok I see why now. On Ubuntu if I install libc6-dev 2.36, its /usr/include/x86_64-linux-gnu/sys/mount.h has these new lines which would bring in the definition of struct mount_attr:

```
#ifdef __has_include
# if __has_include ("linux/mount.h")
#  include "linux/mount.h"
# endif
#endif
```

**Comment by ryao** [comment]
That explains things nicely. Thanks for finding it.
