### ISSUE TITLE
SPL and ZFS Kernel Build on 3.12.2

### ISSUE THREAD

**Issue by Podilarius** [openzfs/zfs#1947]
There is an issue compiling both spl and zfs modules against 3.12.2 on Fedora 19 x64.
linux-3.12.2]# make all
make[1]: Nothing to be done for all'.
make[1]: Nothing to be done forrelocs'.
CHK include/config/kernel.release
CHK include/generated/uapi/linux/version.h
CHK include/generated/utsrelease.h
CALL scripts/checksyscalls.sh
CHK include/generated/compile.h
make[3]: `arch/x86/realmode/rm/realmode.bin' is up to date.
CC spl/spl/spl-proc.o
CC spl/spl/spl-kmem.o
In file included from /usr/src/linux-3.12.2/include/spl/sys/types.h:44:0,
from /usr/src/linux-3.12.2/include/spl/sys/kmem.h:37,
from spl/spl/spl-kmem.c:27:
/usr/src/linux-3.12.2/include/spl/linux/mm_compat.h:254:15: error: unknown field âshrinkâ specified in initializer
static struct shrinker s = { \
^
spl/spl/spl-kmem.c:842:1: note: in expansion of macro âSPL_SHRINKER_DECLAREâ
SPL_SHRINKER_DECLARE(spl_kmem_cache_shrinker,
^
/usr/src/linux-3.12.2/include/spl/linux/mm_compat.h:254:15: warning: initialization from incompatible pointer type [enabled by default]
static struct shrinker s = { \
^
spl/spl/spl-kmem.c:842:1: note: in expansion of macro âSPL_SHRINKER_DECLAREâ
SPL_SHRINKER_DECLARE(spl_kmem_cache_shrinker,
^
/usr/src/linux-3.12.2/include/spl/linux/mm_compat.h:254:15: warning: (near initialization for âspl_kmem_cache_shrinker.count_objectsâ) [enabled by default]
static struct shrinker s = { \
^
spl/spl/spl-kmem.c:842:1: note: in expansion of macro âSPL_SHRINKER_DECLAREâ
SPL_SHRINKER_DECLARE(spl_kmem_cache_shrinker,
^
make[2]: **\* [spl/spl/spl-kmem.o] Error 1
make[1]: **\* [spl/spl] Error 2
make: **\* [spl] Error 2

After forcing SPL to use new shrinker code:
linux-3.12.2]# make all
make[1]: Nothing to be done for all'.
make[1]: Nothing to be done forrelocs'.
CHK include/config/kernel.release
CHK include/generated/uapi/linux/version.h
CHK include/generated/utsrelease.h
CALL scripts/checksyscalls.sh
CHK include/generated/compile.h
make[3]: `arch/x86/realmode/rm/realmode.bin' is up to date.
CC fs/zfs/zfs/zfs_vfsops.o
fs/zfs/zfs/zfs_vfsops.c: In function âzfs_sb_pruneâ:
fs/zfs/zfs/zfs_vfsops.c:1076:23: error: âstruct shrinkerâ has no member named âshrinkâ
objects = (shrinker->shrink)(shrinker, &sc);
^
make[3]: **\* [fs/zfs/zfs/zfs_vfsops.o] Error 1
make[2]: **\* [fs/zfs/zfs] Error 2
make[1]: **\* [fs/zfs] Error 2
make: **\* [fs] Error 2

I guess this will also happen on newer kernels. Still complaining about shrinker code.
