### ISSUE TITLE
error: implicit declaration of function ‘__arc_shrinker_func’

### ISSUE THREAD

**Issue by kiranfractal** [openzfs/zfs#2919]
I am installing zfs by enabling zfs-testing and it failed.
## Terminal output:

Loading new zfs-0.6.3 DKMS files...
Building for 2.6.32-504.1.3.el6.x86_64
Building initial module for 2.6.32-504.1.3.el6.x86_64
Error! Bad return status for module build on kernel: 2.6.32-504.1.3.el6.x86_64 (x86_64)
Consult /var/lib/dkms/zfs/0.6.3/build/make.log for more information.
warning: %post(zfs-dkms-0.6.3-159_gc944be5.el6.noarch) scriptlet failed, exit status 10
  Installing : zfs-0.6.3-159_gc944be5.el6.x86_64                                                                                                         3/3 
  Verifying  : zfs-dkms-0.6.3-159_gc944be5.el6.noarch                                                                                                    1/3 
  Verifying  : zfs-0.6.3-159_gc944be5.el6.x86_64                                                                                                         2/3 
  Verifying  : libzfs2-0.6.3-159_gc944be5.el6.x86_64                                                                                                     3/3 
## /var/lib/dkms/zfs/0.6.3/build/make.log file snippet

Making all in module
make[2]: Entering directory `/var/lib/dkms/zfs/0.6.3/build/module'
make -C /lib/modules/2.6.32-504.1.3.el6.x86_64/build SUBDIRS=`pwd`CONFIG_ZFS=m modules
make[3]: Entering directory`/usr/src/kernels/2.6.32-504.1.3.el6.x86_64'
  CC [M]  /var/lib/dkms/zfs/0.6.3/build/module/avl/../../module/avl/avl.o
  LD [M]  /var/lib/dkms/zfs/0.6.3/build/module/avl/zavl.o
  CC [M]  /var/lib/dkms/zfs/0.6.3/build/module/nvpair/../../module/nvpair/nvpair.o
  CC [M]  /var/lib/dkms/zfs/0.6.3/build/module/nvpair/../../module/nvpair/fnvpair.o
  CC [M]  /var/lib/dkms/zfs/0.6.3/build/module/nvpair/../../module/nvpair/nvpair_alloc_spl.o
  CC [M]  /var/lib/dkms/zfs/0.6.3/build/module/nvpair/../../module/nvpair/nvpair_alloc_fixed.o
  LD [M]  /var/lib/dkms/zfs/0.6.3/build/module/nvpair/znvpair.o
  CC [M]  /var/lib/dkms/zfs/0.6.3/build/module/unicode/../../module/unicode/u8_textprep.o
  CC [M]  /var/lib/dkms/zfs/0.6.3/build/module/unicode/../../module/unicode/uconv.o
  LD [M]  /var/lib/dkms/zfs/0.6.3/build/module/unicode/zunicode.o
  CC [M]  /var/lib/dkms/zfs/0.6.3/build/module/zcommon/../../module/zcommon/zfs_deleg.o
  CC [M]  /var/lib/dkms/zfs/0.6.3/build/module/zcommon/../../module/zcommon/zfs_prop.o
  CC [M]  /var/lib/dkms/zfs/0.6.3/build/module/zcommon/../../module/zcommon/zprop_common.o
  CC [M]  /var/lib/dkms/zfs/0.6.3/build/module/zcommon/../../module/zcommon/zfs_namecheck.o
  CC [M]  /var/lib/dkms/zfs/0.6.3/build/module/zcommon/../../module/zcommon/zfs_comutil.o
  CC [M]  /var/lib/dkms/zfs/0.6.3/build/module/zcommon/../../module/zcommon/zfs_fletcher.o
  CC [M]  /var/lib/dkms/zfs/0.6.3/build/module/zcommon/../../module/zcommon/zfs_uio.o
  CC [M]  /var/lib/dkms/zfs/0.6.3/build/module/zcommon/../../module/zcommon/zpool_prop.o
  LD [M]  /var/lib/dkms/zfs/0.6.3/build/module/zcommon/zcommon.o
  CC [M]  /var/lib/dkms/zfs/0.6.3/build/module/zfs/../../module/zfs/arc.o
/var/lib/dkms/zfs/0.6.3/build/module/zfs/../../module/zfs/arc.c:2506: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘__arc_shrinker_func’
/var/lib/dkms/zfs/0.6.3/build/module/zfs/../../module/zfs/arc.c: In function ‘arc_shrinker_func’:
/var/lib/dkms/zfs/0.6.3/build/module/zfs/../../module/zfs/arc.c:2564: error: implicit declaration of function ‘__arc_shrinker_func’
make[5]: **\* [/var/lib/dkms/zfs/0.6.3/build/module/zfs/../../module/zfs/arc.o] Error 1
make[4]: **\* [/var/lib/dkms/zfs/0.6.3/build/module/zfs] Error 2
make[3]: **\* [_module_/var/lib/dkms/zfs/0.6.3/build/module] Error 2
make[3]: Leaving directory `/usr/src/kernels/2.6.32-504.1.3.el6.x86_64'
make[2]: *** [modules] Error 2
make[2]: Leaving directory`/var/lib/dkms/zfs/0.6.3/build/module'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/var/lib/dkms/zfs/0.6.3/build'
make: **\* [all] Error 2

**Comment by behlendorf** [comment]
@kiranfractal Sorry about the delay, @nedbass sorted out the build issue and I expect we'll get those change merged to master this week.
