### ISSUE TITLE
Error building osd-zfs during Lustre installation

### ISSUE THREAD

**Issue by vinkamath** [openzfs/zfs#12192]
### System information

Type | Version/Name
 --- | ---
Distribution Name	| CentOS
Distribution Version	| CentOS 8
Linux Kernel	| 4.18.0-240.1.1.el8_3.x86_64 
Architecture	| x86_64 
ZFS Version	| 2.0.0-1
SPL Version	|

### Describe the problem you're observing
I ran into this error when trying to install Lustre server packages. I'm reporting this here because the error message is a missing zfs header file. Let me know if this a Lustre bug and I should report it there instead.

 Installing lustre-zfs-dkms throws the following error:
```
Error! Bad return status for module build on kernel: 4.18.0-240.1.1.el8_3.x86_64 (x86_64)
Consult /var/lib/dkms/lustre-zfs/2.14.0/build/make.log for more information.
warning: %post(lustre-zfs-dkms-2.14.0-1.el8.noarch) scriptlet failed, exit status 10

Error in POSTIN scriptlet in rpm package lustre-zfs-dkms
 ```

### Describe how to reproduce the problem

```
DIST="el8_3"
yum -y install epel-release
yum -y install http://download.zfsonlinux.org/epel/zfs-release.$DIST.noarch.rpm


# Add the power tools repo, if isn't already there
yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
yum config-manager --set-enabled powertools


# Download lustre
PACKAGE="lustre"
ARCH="x86_64"
[ ! -d  $PACKAGE ] && mkdir $PACKAGE
cd $PACKAGE
wget -r -nc -nd -level=0 -R "*index.html*,*debuginfo*" -np https://downloads.whamcloud.com/public/lustre/latest-feature-release/el8.3.2011/server/RPMS/x86_64/

# Install lustre packages
yum -y install --nogpg ./lustre-zfs-dkms-2.14.0-1.el8.noarch.rpm ./lustre-osd-zfs-mount-2.14.0-1.el8.x86_64.rpm ./kmod-lustre-2.14.0-1.el8.x86_64.rpm ./kmod-lustre-osd-zfs-2.14.0-1.el8.x86_64.rpm ./libzfs4-2.0.0-1.el8.x86_64.rpm ./kmod-zfs-4.18.0-240.1.1.el8_lustre.x86_64-2.0.0-1.el8.x86_64.rpm ./zfs-kmod-debugsource-2.0.0-1.el8.x86_64.rpm ./kmod-zfs-4.18.0-240.1.1.el8_lustre.x86_64-2.0.0-1.el8.x86_64.rpm ./zfs-2.0.0-1.el8.x86_64.rpm ./libzpool4-2.0.0-1.el8.x86_64.rpm ./libnvpair3-2.0.0-1.el8.x86_64.rpm ./libuutil3-2.0.0-1.el8.x86_64.rpm ./zfs-dkms-2.0.0-1.el8.noarch.rpm
yum -y install ./lustre-2.14.0-1.el8.x86_64.rpm lustre-devel-2.14.0-1.el8.x86_64.rpm ./lustre-tests-2.14.0-1.el8.x86_64.rpm
yum install ./python3-pyzfs-2.0.0-1.el8.noarch.rpm ./zfs-dracut-2.0.0-1.el8.noarch.rpm ./zfs-test-2.0.0-1.el8.x86_64.rpm

# This package has dependencies I don't know how to resolve
# yum install lustre-resource-agents-2.14.0-1.el8.x86_64.rpm

cd ../
```
To replicate this issue, I rebuilt all lustre zfs kernel modules

```
dkms remove -m lustre-zfs -v 2.14.0 -k $(uname -r)
dkms build -m lustre-zfs -v 2.14.0
```
Error message:
```
<snip>

config.status: executing depfiles commands
config.status: executing libtool commands

CC:            gcc
LD:            /bin/ld -m elf_x86_64
CPPFLAGS:      -include /var/lib/dkms/lustre-zfs/2.14.0/build/undef.h -include /var/lib/dkms/lustre-zfs/2.14.0/build/config.h -I/var/lib/dkms/lustre-zfs/2.14.0/build/lnet/include/uapi -I/var/lib/dkms/lustre-zfs/2.14.0/build/lustre/include/uapi -I/var/lib/dkms/lustre-zfs/2.14.0/build/libcfs/include -I/var/lib/dkms/lustre-zfs/2.14.0/build/lnet/utils -I/var/lib/dkms/lustre-zfs/2.14.0/build/lustre/include 
CFLAGS:        -g -O2 -Wall -Werror
EXTRA_KCFLAGS: -include /var/lib/dkms/lustre-zfs/2.14.0/build/undef.h -include /var/lib/dkms/lustre-zfs/2.14.0/build/config.h  -g -I/var/lib/dkms/lustre-zfs/2.14.0/build/libcfs/include -I/var/lib/dkms/lustre-zfs/2.14.0/build/libcfs/include/libcfs -I/var/lib/dkms/lustre-zfs/2.14.0/build/lnet/include/uapi -I/var/lib/dkms/lustre-zfs/2.14.0/build/lnet/include -I/var/lib/dkms/lustre-zfs/2.14.0/build/lustre/include/uapi -I/var/lib/dkms/lustre-zfs/2.14.0/build/lustre/include -Wno-format-truncation -Wno-stringop-truncation -Wno-stringop-overflow

Type 'make' to build Lustre.

Building module:
cleaning build area...
make -j8 KERNELRELEASE=4.18.0-240.1.1.el8_3.x86_64................(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.18.0-240.1.1.el8_3.x86_64 (x86_64)
Consult /var/lib/dkms/lustre-zfs/2.14.0/build/make.log for more information.

```

Relevant messages from make.log:
```
<snip>
  CC [M]  /var/lib/dkms/lustre-zfs/2.14.0/build/lustre/ofd/ofd_fs.o
  CC [M]  /var/lib/dkms/lustre-zfs/2.14.0/build/lustre/llite/crypto.o
  CC [M]  /var/lib/dkms/lustre-zfs/2.14.0/build/lustre/osd-zfs/osd_handler.o
  CC [M]  /var/lib/dkms/lustre-zfs/2.14.0/build/lustre/mgs/mgs_barrier.o
In file included from /usr/src/zfs-2.0.0/include/sys/arc.h:32,
                 from /var/lib/dkms/lustre-zfs/2.14.0/build/lustre/osd-zfs/osd_internal.h:51,
                 from /var/lib/dkms/lustre-zfs/2.14.0/build/lustre/osd-zfs/osd_handler.c:52:
/usr/src/zfs-2.0.0/include/sys/zfs_context.h:45:10: fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>
          ^~~~~~~~~~~~~
compilation terminated.
make[6]: *** [scripts/Makefile.build:315: /var/lib/dkms/lustre-zfs/2.14.0/build/lustre/osd-zfs/osd_handler.o] Error 1
make[5]: *** [scripts/Makefile.build:556: /var/lib/dkms/lustre-zfs/2.14.0/build/lustre/osd-zfs] Error 2
make[5]: *** Waiting for unfinished jobs....
  CC [M]  /var/lib/dkms/lustre-zfs/2.14.0/build/lustre/osc/osc_dev.o
  CC [M]  /var/lib/dkms/lustre-zfs/2.14.0/build/lustre/obdclass/llog_osd.o
  CC [M]  /var/lib/dkms/lustre-zfs/2.14.0/build/lustre/ofd/ofd_trans.o

<snip>
```

### Include any warning/errors/backtraces from the system logs
N/A

**Comment by rincebrain** [comment]
As this header exists in the OpenZFS codebase and this compile error does not happen with it, I believe it would be an issue specific to their packages.

**Comment by vinkamath** [comment]
This is a fresh installation. I do have glibc-devel installed.

**Comment by rincebrain** [comment]
The most straightforward way to confirm this is a problem specific to their packages would be for you to either grab one of the release tarballs or [add the openzfs centos/rhel 8 package repo](https://openzfs.github.io/openzfs-docs/Getting%20Started/RHEL%20and%20CentOS.html), install/build the zfs-dkms package, and see if it fails the same way. (I'd suggest 2.0.4, since their package seems to claim to be 2.0.0 based on its path in /usr/src.)

**Comment by vinkamath** [comment]
I'm able to build zfs modules independently from source just fine. The issue only arises when building lustre modules. Closing this issue.

**Comment by MrrDrr** [comment]
> I'm able to build zfs modules independently from source just fine. The issue only arises when building lustre modules. Closing this issue.

Has the problem been solved? How to solve it? I compiled and installed zfs2.1.1 on my server, and then encountered the same problem when I tried to compile lustre2.12.7.

Error message when I try to compile lustre2.12.7:

`Type 'make' to build Lustre.
+ make -j48 -s
Making all in .
In file included from /var/lib/dkms/zfs/2.1.1/source/include/sys/arc.h:32:0,
                 from /tmp/rpmbuild-lustre-root-VIPY3oWB/BUILD/lustre-2.12.7/lustre/osd-zfs/osd_internal.h:51,
                 from /tmp/rpmbuild-lustre-root-VIPY3oWB/BUILD/lustre-2.12.7/lustre/osd-zfs/osd_handler.c:52:
/var/lib/dkms/zfs/2.1.1/source/include/sys/zfs_context.h:45:23: fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>
                       ^
compilation terminated.
In file included from /var/lib/dkms/zfs/2.1.1/source/include/sys/arc.h:32:0,
                 from /tmp/rpmbuild-lustre-root-VIPY3oWB/BUILD/lustre-2.12.7/lustre/osd-zfs/osd_internal.h:51,
                 from /tmp/rpmbuild-lustre-root-VIPY3oWB/BUILD/lustre-2.12.7/lustre/osd-zfs/osd_lproc.c:45:
/var/lib/dkms/zfs/2.1.1/source/include/sys/zfs_context.h:45:23: fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>
                       ^
compilation terminated.
make[7]: *** [/tmp/rpmbuild-lustre-root-VIPY3oWB/BUILD/lustre-2.12.7/lustre/osd-zfs/osd_handler.o] Error 1
make[7]: *** Waiting for unfinished jobs....
make[7]: *** [/tmp/rpmbuild-lustre-root-VIPY3oWB/BUILD/lustre-2.12.7/lustre/osd-zfs/osd_lproc.o] Error 1
make[6]: *** [/tmp/rpmbuild-lustre-root-VIPY3oWB/BUILD/lustre-2.12.7/lustre/osd-zfs] Error 2
make[6]: *** Waiting for unfinished jobs....
make[5]: *** [/tmp/rpmbuild-lustre-root-VIPY3oWB/BUILD/lustre-2.12.7/lustre] Error 2
make[4]: *** [_module_/tmp/rpmbuild-lustre-root-VIPY3oWB/BUILD/lustre-2.12.7] Error 2
make[3]: *** [modules] Error 2
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
error: Bad exit status from /tmp/rpmbuild-lustre-root-VIPY3oWB/TMP/rpm-tmp.R6KlF1 (%build)


RPM build errors:
    Bad exit status from /tmp/rpmbuild-lustre-root-VIPY3oWB/TMP/rpm-tmp.R6KlF1 (%build)
make: *** [rpms] Error 1
`

**Comment by rincebrain** [comment]
> > I'm able to build zfs modules independently from source just fine. The issue only arises when building lustre modules. Closing this issue.
> 
> Has the problem been solved? How to solve it? I compiled and installed zfs2.1.1 on my server, and then encountered the same problem when I tried to compile lustre2.12.7.
> 
> Error message when I try to compile lustre2.12.7:
> 
> `
> Type 'make' to build Lustre.
> + make -j48 -s
> Making all in .
> In file included from /var/lib/dkms/zfs/2.1.1/source/include/sys/arc.h:32:0,
> from /tmp/rpmbuild-lustre-root-VIPY3oWB/BUILD/lustre-2.12.7/lustre/osd-zfs/osd_internal.h:51,
> from /tmp/rpmbuild-lustre-root-VIPY3oWB/BUILD/lustre-2.12.7/lustre/osd-zfs/osd_handler.c:52:
> /var/lib/dkms/zfs/2.1.1/source/include/sys/zfs_context.h:45:23: fatal error: sys/types.h: No such file or directory
> #include <sys/types.h>
> ^
> compilation terminated.
> In file included from /var/lib/dkms/zfs/2.1.1/source/include/sys/arc.h:32:0,
> from /tmp/rpmbuild-lustre-root-VIPY3oWB/BUILD/lustre-2.12.7/lustre/osd-zfs/osd_internal.h:51,
> from /tmp/rpmbuild-lustre-root-VIPY3oWB/BUILD/lustre-2.12.7/lustre/osd-zfs/osd_lproc.c:45:
> /var/lib/dkms/zfs/2.1.1/source/include/sys/zfs_context.h:45:23: fatal error: sys/types.h: No such file or directory
> #include <sys/types.h>
> ^
> compilation terminated.
> make[7]: *** [/tmp/rpmbuild-lustre-root-VIPY3oWB/BUILD/lustre-2.12.7/lustre/osd-zfs/osd_handler.o] Error 1
> make[7]: *** Waiting for unfinished jobs....
> make[7]: *** [/tmp/rpmbuild-lustre-root-VIPY3oWB/BUILD/lustre-2.12.7/lustre/osd-zfs/osd_lproc.o] Error 1
> make[6]: *** [/tmp/rpmbuild-lustre-root-VIPY3oWB/BUILD/lustre-2.12.7/lustre/osd-zfs] Error 2
> make[6]: *** Waiting for unfinished jobs....
> make[5]: *** [/tmp/rpmbuild-lustre-root-VIPY3oWB/BUILD/lustre-2.12.7/lustre] Error 2
> make[4]: *** [_module_/tmp/rpmbuild-lustre-root-VIPY3oWB/BUILD/lustre-2.12.7] Error 2
> make[3]: *** [modules] Error 2
> make[2]: *** [all-recursive] Error 1
> make[1]: *** [all] Error 2
> error: Bad exit status from /tmp/rpmbuild-lustre-root-VIPY3oWB/TMP/rpm-tmp.R6KlF1 (%build)
> 
> RPM build errors:
> Bad exit status from /tmp/rpmbuild-lustre-root-VIPY3oWB/TMP/rpm-tmp.R6KlF1 (%build)
> make: *** [rpms] Error 1
> `

This doesn't appear to be a bug in OpenZFS, but in the Lustre modules. You should probably ask the Lustre devs about it.
