### PR TITLE
block_cloning: multiple bugfixes on FreeBSD

### PR DESCRIPTION
**Pull request by mmatuska**
### Motivation and Context
FreeBSD:
- if copying files on the same dataset and block_cloning is not enabled, the copy is refused and EXDEV is returned
- zfs_freebsd_copy_file_range() may panic if 

### Description
Fall back to vn_generic_copy_file_range() if EXDEV is returned.
Use a_outcred if a_fsizetd is NULL

### How Has This Been Tested?
Local testing

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by mjguzik — APPROVED** [review]

**Comment by mcmilk** [comment]
Does not build on my FreeBSD 13.1 box:

```
lk/src/zfs.mmatuska/module/os/freebsd/zfs/zfs_vnops_os.c -o zfs_vnops_os.o
/home/mcmilk/src/zfs.mmatuska/module/os/freebsd/zfs/zfs_vnops_os.c:6286:6: error: incompatible pointer types assigning to 'struct thread *' from 'struct ucred *' [-Werror,-Wincompatible-pointer-types]
                td = ap->a_outcred;
                   ^ ~~~~~~~~~~~~~
/home/mcmilk/src/zfs.mmatuska/module/os/freebsd/zfs/zfs_vnops_os.c:6288:6: error: incompatible pointer types assigning to 'struct thread *' from 'struct ucred *' [-Werror,-Wincompatible-pointer-types]
                td = ap->a_fsizetd->td_ucred;
                   ^ ~~~~~~~~~~~~~~~~~~~~~~~
/home/mcmilk/src/zfs.mmatuska/module/os/freebsd/zfs/zfs_vnops_os.c:6291:33: error: incompatible pointer types passing 'struct thread *' to parameter of type 'cred_t *' (aka 'struct ucred *') [-Werror,-Wincompatible-pointer-types]
            ap->a_outoffp, ap->a_lenp, td);
                                       ^~
/home/mcmilk/src/zfs.mmatuska/include/sys/zfs_vnops.h:35:25: note: passing argument to parameter here
    uint64_t *, cred_t *);
                        ^
3 errors generated.
*** Error code 1

```

**Comment by mmatuska** [comment]
Closed in favor of #14723
